//! Focused tests for the pure core of src/crdt_engine/block_ops.rs:
//! position resolution, ledger hash determinism (against reference vectors
//! generated with the TS canonicalPayloadHash algorithm), the in-Doc
//! operation ledger, and text-edit application against an in-memory Doc
//! built with the module's own insert code.
//!
//! These tests exercise Garden's real library implementation through its
//! deliberately narrow, doc-hidden parity-test surface.

use garden_lib::crdt_engine::block_ops::{
    block_edits_from_payload, block_ids_in_fragment, canonical_payload_hash, clamp_index,
    collect_block_ids, edit_block_text, find_block_in_fragment, insert_blocks_into_fragment,
    prune_ledger, read_block_id_from_json, read_ledger_entry, resolve_insert_index,
    text_edit_ops_from_payload, update_block_attributes, write_ledger_entry, BlockTextEditOp,
    LedgerWriteFields,
};
use garden_lib::crdt_engine::projection::ydoc_to_tiptap_json;
use serde_json::{json, Map, Value};
use yrs::types::xml::XmlFragment;
use yrs::{Doc, Transact, XmlFragmentRef};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn paragraph(block_id: &str, text: &str) -> Value {
    json!({
        "type": "paragraph",
        "attrs": { "data-block-id": block_id },
        "content": [{ "type": "text", "text": text }],
    })
}

fn new_doc() -> (Doc, XmlFragmentRef) {
    let doc = Doc::new();
    let fragment = doc.get_or_insert_xml_fragment("content");
    (doc, fragment)
}

/// Plain text of each top-level block, read from the projected TipTap JSON.
fn block_texts(doc: &Doc) -> Vec<String> {
    let tiptap = ydoc_to_tiptap_json(doc);
    tiptap
        .get("content")
        .and_then(Value::as_array)
        .map(|blocks| blocks.iter().map(inline_text).collect())
        .unwrap_or_default()
}

fn inline_text(node: &Value) -> String {
    if node.get("type").and_then(Value::as_str) == Some("text") {
        return node
            .get("text")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string();
    }
    node.get("content")
        .and_then(Value::as_array)
        .map(|children| children.iter().map(inline_text).collect())
        .unwrap_or_default()
}

fn insert_op(offset: f64, text: &str) -> Value {
    json!({ "type": "insert", "offset": offset, "text": text })
}

fn delete_op(offset: f64, length: f64) -> Value {
    json!({ "type": "delete", "offset": offset, "length": length })
}

fn ops_from(values: Vec<Value>) -> Vec<BlockTextEditOp> {
    text_edit_ops_from_payload(Some(&Value::Array(values)))
}

// ---------------------------------------------------------------------------
// Canonical payload hash (reference vectors generated by running the exact
// TS canonicalize + fnv1a32 implementation under node)
// ---------------------------------------------------------------------------

#[test]
fn canonical_payload_hash_matches_ts_reference_vectors() {
    assert_eq!(canonical_payload_hash(&json!({})), "5465b825");
    assert_eq!(
        canonical_payload_hash(&json!({
            "blockId": "b1",
            "operations": [{ "type": "insert", "offset": 0, "text": "héllo 😀" }],
        })),
        "318b38ba",
        "UTF-16 code-unit hashing (surrogate pairs) must match charCodeAt"
    );
    assert_eq!(
        canonical_payload_hash(&json!({
            "a": 1,
            "b": [true, null, "x"],
            "c": { "z": 2.5, "y": "q\nr" },
        })),
        "21942f08",
        "sorted keys, escapes, and float formatting must match JSON.stringify"
    );
}

#[test]
fn canonical_payload_hash_is_deterministic_and_payload_sensitive() {
    let payload = json!({ "blockId": "b1", "index": 2 });
    assert_eq!(
        canonical_payload_hash(&payload),
        canonical_payload_hash(&payload.clone())
    );
    assert_ne!(
        canonical_payload_hash(&payload),
        canonical_payload_hash(&json!({ "blockId": "b1", "index": 3 }))
    );
}

// ---------------------------------------------------------------------------
// Insert position resolution
// ---------------------------------------------------------------------------

#[test]
fn resolve_insert_index_matches_ts_semantics() {
    // Default: append at end.
    assert_eq!(resolve_insert_index(None, false, None, 5), 5.0);
    // Reference block: before/after.
    assert_eq!(resolve_insert_index(Some(2), true, None, 5), 2.0);
    assert_eq!(resolve_insert_index(Some(2), false, None, 5), 3.0);
    // Reference block wins over an index hint.
    assert_eq!(resolve_insert_index(Some(1), false, Some(4.0), 5), 2.0);
    // Positive hint clamps to blockCount.
    assert_eq!(resolve_insert_index(None, false, Some(3.0), 5), 3.0);
    assert_eq!(resolve_insert_index(None, false, Some(99.0), 5), 5.0);
    // Negative hint: max(0, blockCount + 1 + hint).
    assert_eq!(resolve_insert_index(None, false, Some(-1.0), 5), 5.0);
    assert_eq!(resolve_insert_index(None, false, Some(-3.0), 5), 3.0);
    assert_eq!(resolve_insert_index(None, false, Some(-99.0), 5), 0.0);
}

#[test]
fn clamp_index_floors_and_bounds() {
    assert_eq!(clamp_index(2.7, 5), 2);
    assert_eq!(clamp_index(-3.0, 5), 0);
    assert_eq!(clamp_index(7.0, 5), 5);
    assert_eq!(clamp_index(f64::NAN, 5), 5);
    assert_eq!(clamp_index(f64::INFINITY, 5), 5);
}

// ---------------------------------------------------------------------------
// Block insertion against an in-memory Doc
// ---------------------------------------------------------------------------

#[test]
fn insert_blocks_appends_and_inserts_at_position() {
    let (doc, fragment) = new_doc();
    {
        let mut txn = doc.transact_mut();
        let ids = insert_blocks_into_fragment(
            &mut txn,
            &fragment,
            &[paragraph("b1", "Hello world"), paragraph("b2", "Second")],
            None,
        )
        .expect("append");
        assert_eq!(ids, vec!["b1", "b2"]);

        // Insert before everything (position 0).
        let ids = insert_blocks_into_fragment(
            &mut txn,
            &fragment,
            &[paragraph("b0", "First")],
            Some(0.0),
        )
        .expect("prepend");
        assert_eq!(ids, vec!["b0"]);

        assert_eq!(
            block_ids_in_fragment(&txn, &fragment),
            vec!["b0", "b1", "b2"]
        );
        let (_, index) = find_block_in_fragment(&txn, &fragment, "b2").expect("find b2");
        assert_eq!(index, 2);
        assert!(find_block_in_fragment(&txn, &fragment, "nope").is_none());
    }
    assert_eq!(block_texts(&doc), vec!["First", "Hello world", "Second"]);
}

#[test]
fn insert_blocks_validates_before_mutating() {
    let (doc, fragment) = new_doc();
    let mut txn = doc.transact_mut();

    let error = insert_blocks_into_fragment(
        &mut txn,
        &fragment,
        &[paragraph("ok", "fine"), json!({ "type": "paragraph" })],
        None,
    )
    .expect_err("missing id must fail");
    assert!(error.contains("data-block-id"), "got: {error}");
    assert_eq!(fragment.len(&txn), 0, "failed insert must not mutate");

    let error = insert_blocks_into_fragment(
        &mut txn,
        &fragment,
        &[json!({ "type": "text", "text": "loose", "attrs": { "data-block-id": "t1" } })],
        None,
    )
    .expect_err("top-level text must fail");
    assert!(error.contains("text node"), "got: {error}");
    assert_eq!(fragment.len(&txn), 0);
}

#[test]
fn read_block_id_from_json_mirrors_ts_fallbacks() {
    assert_eq!(
        read_block_id_from_json(&json!({ "attrs": { "data-block-id": "a" } })).as_deref(),
        Some("a")
    );
    // blockId fallback, including when data-block-id is explicitly null.
    assert_eq!(
        read_block_id_from_json(&json!({ "attrs": { "blockId": "b" } })).as_deref(),
        Some("b")
    );
    assert_eq!(
        read_block_id_from_json(&json!({ "attrs": { "data-block-id": null, "blockId": "c" } }))
            .as_deref(),
        Some("c")
    );
    // Non-string and empty ids do not count.
    assert_eq!(
        read_block_id_from_json(&json!({ "attrs": { "data-block-id": 5 } })),
        None
    );
    assert_eq!(
        read_block_id_from_json(&json!({ "attrs": { "data-block-id": "" } })),
        None
    );
    assert_eq!(read_block_id_from_json(&json!({})), None);
}

// ---------------------------------------------------------------------------
// Text edits
// ---------------------------------------------------------------------------

#[test]
fn edit_block_text_applies_ops_in_descending_offset_order() {
    let (doc, fragment) = new_doc();
    {
        let mut txn = doc.transact_mut();
        insert_blocks_into_fragment(&mut txn, &fragment, &[paragraph("b1", "Hello world")], None)
            .unwrap();
        let (element, _) = find_block_in_fragment(&txn, &fragment, "b1").unwrap();
        // Payload order is low-offset first; application must be high-offset
        // first so earlier edits don't shift later offsets.
        let ops = ops_from(vec![insert_op(0.0, "A"), insert_op(11.0, " tail")]);
        let result = edit_block_text(&mut txn, &element, &ops).expect("edit");
        assert_eq!(result.block_id, "b1");
        assert_eq!(result.length_before, 11);
        assert_eq!(result.length_after, 17);
        assert_eq!(result.applied, 2);
    }
    assert_eq!(block_texts(&doc), vec!["AHello world tail"]);
}

#[test]
fn edit_block_text_delete_and_empty_insert_semantics() {
    let (doc, fragment) = new_doc();
    {
        let mut txn = doc.transact_mut();
        insert_blocks_into_fragment(&mut txn, &fragment, &[paragraph("b1", "Hello world")], None)
            .unwrap();
        let (element, _) = find_block_in_fragment(&txn, &fragment, "b1").unwrap();
        // Delete " world"; over-long ranges clamp; empty insert is skipped
        // but a positive-length delete counts as applied.
        let ops = ops_from(vec![insert_op(3.0, ""), delete_op(5.0, 600.0)]);
        let result = edit_block_text(&mut txn, &element, &ops).expect("edit");
        assert_eq!(result.length_before, 11);
        assert_eq!(result.length_after, 5);
        assert_eq!(result.applied, 1, "empty insert skipped, delete applied");
    }
    assert_eq!(block_texts(&doc), vec!["Hello"]);
}

#[test]
fn edit_block_text_uses_utf16_offsets() {
    let (doc, fragment) = new_doc();
    {
        let mut txn = doc.transact_mut();
        // "a😀b" is 4 UTF-16 units (emoji = surrogate pair) but 6 bytes.
        insert_blocks_into_fragment(&mut txn, &fragment, &[paragraph("b1", "a😀b")], None).unwrap();
        let (element, _) = find_block_in_fragment(&txn, &fragment, "b1").unwrap();
        let result =
            edit_block_text(&mut txn, &element, &ops_from(vec![insert_op(3.0, "X")])).unwrap();
        assert_eq!(result.length_before, 4);
        assert_eq!(result.length_after, 5);
    }
    assert_eq!(block_texts(&doc), vec!["a😀Xb"]);

    let (doc, fragment) = new_doc();
    {
        let mut txn = doc.transact_mut();
        insert_blocks_into_fragment(&mut txn, &fragment, &[paragraph("b1", "a😀b")], None).unwrap();
        let (element, _) = find_block_in_fragment(&txn, &fragment, "b1").unwrap();
        let result =
            edit_block_text(&mut txn, &element, &ops_from(vec![delete_op(1.0, 2.0)])).unwrap();
        assert_eq!(result.length_after, 2);
    }
    assert_eq!(block_texts(&doc), vec!["ab"]);
}

#[test]
fn edit_block_text_inherits_formatting_mid_text() {
    let (doc, fragment) = new_doc();
    {
        let mut txn = doc.transact_mut();
        insert_blocks_into_fragment(
            &mut txn,
            &fragment,
            &[json!({
                "type": "paragraph",
                "attrs": { "data-block-id": "b1" },
                "content": [{ "type": "text", "text": "Bold", "marks": [{ "type": "bold" }] }],
            })],
            None,
        )
        .unwrap();
        let (element, _) = find_block_in_fragment(&txn, &fragment, "b1").unwrap();
        // Default inheritFormat splices into the bold run with bold attrs.
        edit_block_text(&mut txn, &element, &ops_from(vec![insert_op(2.0, "xx")])).unwrap();
    }
    let tiptap = ydoc_to_tiptap_json(&doc);
    let content = tiptap["content"][0]["content"]
        .as_array()
        .expect("inline content");
    assert_eq!(
        content.len(),
        1,
        "inherited format keeps one bold run: {content:?}"
    );
    assert_eq!(content[0]["text"], "Boxxld");
    assert_eq!(content[0]["marks"][0]["type"], "bold");
}

#[test]
fn edit_block_text_errors_when_block_has_no_text_segments() {
    let (doc, fragment) = new_doc();
    let mut txn = doc.transact_mut();
    insert_blocks_into_fragment(
        &mut txn,
        &fragment,
        &[json!({ "type": "horizontalRule", "attrs": { "data-block-id": "hr1" } })],
        None,
    )
    .unwrap();
    let (element, _) = find_block_in_fragment(&txn, &fragment, "hr1").unwrap();
    let error = edit_block_text(&mut txn, &element, &ops_from(vec![insert_op(0.0, "x")]))
        .expect_err("no text segments");
    assert!(error.contains("no text segments"), "got: {error}");
}

// ---------------------------------------------------------------------------
// Attribute updates
// ---------------------------------------------------------------------------

#[test]
fn update_block_attributes_sets_removes_and_skips_equal_primitives() {
    let (doc, fragment) = new_doc();
    let mut txn = doc.transact_mut();
    insert_blocks_into_fragment(
        &mut txn,
        &fragment,
        &[json!({
            "type": "listItem",
            "attrs": { "data-block-id": "b1", "listType": "bullet", "checked": false },
        })],
        None,
    )
    .unwrap();
    let (element, _) = find_block_in_fragment(&txn, &fragment, "b1").unwrap();

    let mut attrs = Map::new();
    attrs.insert("listType".to_string(), json!("bullet")); // unchanged primitive
    attrs.insert("checked".to_string(), json!(true)); // changed
    attrs.insert("indent".to_string(), json!(2)); // new
    attrs.insert("language".to_string(), Value::Null); // absent → no-op
    let changed = update_block_attributes(&mut txn, &element, &attrs);
    assert_eq!(changed, vec!["checked", "indent"]);

    // null removes an existing attribute.
    let mut attrs = Map::new();
    attrs.insert("checked".to_string(), Value::Null);
    let changed = update_block_attributes(&mut txn, &element, &attrs);
    assert_eq!(changed, vec!["checked"]);
    drop(txn);

    let tiptap = ydoc_to_tiptap_json(&doc);
    let block_attrs = &tiptap["content"][0]["attrs"];
    assert_eq!(block_attrs["indent"], json!(2.0));
    assert!(block_attrs.get("checked").is_none());
}

// ---------------------------------------------------------------------------
// Operation ledger
// ---------------------------------------------------------------------------

#[test]
fn ledger_roundtrips_result_envelope_and_hash() {
    let doc = Doc::new();
    let mut txn = doc.transact_mut();

    assert!(read_ledger_entry(&txn, "op-1").is_none());

    let envelope = json!({
        "block_ids": ["b1"],
        "blocks_inserted": 1,
        "blocks_existing": 0,
        "existing_block_ids": [],
        "block_count": 1,
    });
    write_ledger_entry(
        &mut txn,
        "op-1",
        LedgerWriteFields {
            op: "block.insert",
            completed_at: "1760000000000",
            payload_hash: Some("deadbeef".to_string()),
            result: Some(&envelope),
        },
    );

    let hit = read_ledger_entry(&txn, "op-1").expect("replay hit");
    assert_eq!(hit.result, Some(envelope));
    assert_eq!(hit.payload_hash.as_deref(), Some("deadbeef"));
    assert_eq!(hit.completed_at, "1760000000000");
    assert!(read_ledger_entry(&txn, "op-2").is_none());
}

#[test]
fn ledger_drops_oversized_results_but_still_records_application() {
    let doc = Doc::new();
    let mut txn = doc.transact_mut();
    let oversized = json!({ "data": "x".repeat(5000) });
    write_ledger_entry(
        &mut txn,
        "op-big",
        LedgerWriteFields {
            op: "block.editText",
            completed_at: "1760000000000",
            payload_hash: None,
            result: Some(&oversized),
        },
    );
    let hit = read_ledger_entry(&txn, "op-big").expect("applied");
    assert_eq!(
        hit.result, None,
        "results over 4096 UTF-16 units are not cached"
    );
    assert_eq!(hit.payload_hash, None);
}

#[test]
fn prune_ledger_drops_aged_entries_and_caps_count() {
    let doc = Doc::new();
    let mut txn = doc.transact_mut();
    let now: f64 = 1_760_000_000_000.0;

    write_ledger_entry(
        &mut txn,
        "op-ancient",
        LedgerWriteFields {
            op: "block.insert",
            completed_at: "1000", // epoch-millis far past the 7-day window
            payload_hash: None,
            result: None,
        },
    );
    // 1030 fresh entries with strictly increasing timestamps.
    for i in 0..1030 {
        write_ledger_entry(
            &mut txn,
            &format!("op-{i}"),
            LedgerWriteFields {
                op: "block.editText",
                completed_at: &format!("{}", now as i64 - 1030 + i),
                payload_hash: None,
                result: None,
            },
        );
    }

    let removed = prune_ledger(&mut txn, now);
    // 1 aged out + 6 over the 1024 cap (oldest first).
    assert_eq!(removed, 7);
    assert!(read_ledger_entry(&txn, "op-ancient").is_none());
    for i in 0..6 {
        assert!(
            read_ledger_entry(&txn, &format!("op-{i}")).is_none(),
            "op-{i} should be capped out"
        );
    }
    assert!(read_ledger_entry(&txn, "op-6").is_some());
    assert!(read_ledger_entry(&txn, "op-1029").is_some());
}

// ---------------------------------------------------------------------------
// Payload parsers
// ---------------------------------------------------------------------------

#[test]
fn text_edit_ops_parser_mirrors_ts_filtering() {
    let ops = text_edit_ops_from_payload(Some(&json!([
        { "type": "insert", "offset": 2, "text": "hi" },
        { "type": "delete", "offset": 0, "length": 3 },
        { "type": "format", "offset": 0 },          // unsupported type → skipped
        { "type": "insert" },                        // missing offset → skipped
        { "type": "delete", "offset": 1 },           // missing length → skipped
        { "type": "insert", "offset": "4", "text": "s", "inherit_format": false },
    ])));
    assert_eq!(ops.len(), 3);
    match &ops[0] {
        BlockTextEditOp::Insert {
            offset,
            text,
            attrs,
            inherit_format,
        } => {
            assert_eq!(*offset, 2.0);
            assert_eq!(text, "hi");
            assert!(attrs.is_none());
            assert!(inherit_format.is_none());
        }
        other => panic!("expected insert, got {other:?}"),
    }
    match &ops[1] {
        BlockTextEditOp::Delete { offset, length } => {
            assert_eq!(*offset, 0.0);
            assert_eq!(*length, 3.0);
        }
        other => panic!("expected delete, got {other:?}"),
    }
    match &ops[2] {
        BlockTextEditOp::Insert {
            offset,
            inherit_format,
            ..
        } => {
            assert_eq!(*offset, 4.0, "string offsets coerce via Number()");
            assert_eq!(
                *inherit_format,
                Some(false),
                "snake_case inherit_format honored"
            );
        }
        other => panic!("expected insert, got {other:?}"),
    }

    assert!(text_edit_ops_from_payload(Some(&json!("not an array"))).is_empty());
    assert!(text_edit_ops_from_payload(None).is_empty());
}

#[test]
fn text_edit_ops_parser_preserves_attrs_presence() {
    let ops = text_edit_ops_from_payload(Some(&json!([
        { "type": "insert", "offset": 0, "text": "a", "attrs": { "bold": {} } },
        { "type": "insert", "offset": 0, "text": "b", "attrs": null },
    ])));
    match &ops[0] {
        BlockTextEditOp::Insert {
            attrs: Some(map), ..
        } => assert!(map.contains_key("bold")),
        other => panic!("expected insert with attrs, got {other:?}"),
    }
    match &ops[1] {
        // Explicit null attrs → present-but-empty (suppresses inheritance
        // resolution through toFormatAttrs, exactly like the TS handler).
        BlockTextEditOp::Insert {
            attrs: Some(map), ..
        } => assert!(map.is_empty()),
        other => panic!("expected insert with empty attrs, got {other:?}"),
    }
}

#[test]
fn collect_block_ids_supports_all_payload_shapes() {
    let payload = |v: Value| v.as_object().cloned().unwrap();
    assert_eq!(
        collect_block_ids(&payload(json!({ "blockIds": ["a", "b", 3, null] }))),
        vec!["a", "b", "3"],
        "numbers coerce via String(), null dropped"
    );
    assert_eq!(
        collect_block_ids(&payload(json!({ "block_ids": ["x"] }))),
        vec!["x"]
    );
    assert_eq!(
        collect_block_ids(&payload(json!({ "blockId": "solo" }))),
        vec!["solo"]
    );
    assert_eq!(
        collect_block_ids(&payload(json!({ "block_id": "snake" }))),
        vec!["snake"]
    );
    assert!(collect_block_ids(&payload(json!({}))).is_empty());
}

#[test]
fn block_edits_parser_supports_lists_aliases_and_single_form() {
    let payload = |v: Value| v.as_object().cloned().unwrap();

    let edits = block_edits_from_payload(&payload(json!({
        "edits": [
            { "blockId": "b1", "attrs": { "checked": true } },
            { "block_id": "b2", "attributes": { "level": 3 } },
            { "attrs": { "ignored": true } },
        ],
    })));
    assert_eq!(edits.len(), 2, "entries without a blockId are skipped");
    assert_eq!(edits[0].block_id, "b1");
    assert_eq!(edits[0].attrs.get("checked"), Some(&json!(true)));
    assert_eq!(edits[1].block_id, "b2");
    assert_eq!(edits[1].attrs.get("level"), Some(&json!(3)));

    let edits = block_edits_from_payload(&payload(json!({
        "updates": [{ "blockId": "u1", "attrs": {} }],
    })));
    assert_eq!(edits.len(), 1);
    assert_eq!(edits[0].block_id, "u1");

    let edits = block_edits_from_payload(&payload(json!({
        "blockId": "single", "attrs": { "k": "v" },
    })));
    assert_eq!(edits.len(), 1);
    assert_eq!(edits[0].block_id, "single");
    assert_eq!(edits[0].attrs.get("k"), Some(&json!("v")));

    assert!(block_edits_from_payload(&payload(json!({}))).is_empty());
}
