//! Parity tests for the Rust port of parseTipTapWriteContent
//! (src/crdt_engine/content_parse.rs) against fixtures generated by running
//! the ACTUAL TypeScript function:
//! frontend/scripts/generate-content-parse-fixtures.test.mts
//! (run from frontend/: pnpm exec vitest run --config scripts/vitest.fixture.config.ts
//!  scripts/generate-content-parse-fixtures.test.mts).
//!
//! Each fixture dir holds input.txt (raw content), format.txt (format param;
//! "auto" means detection), expected.json ({tiptapJson, derivedTitle,
//! sourceFormat, warnings}).
//!
//! Nondeterminism normalization (mirrored on both sides): ensureBlockIds
//! assigns random `data-block-id: block-<uuid8>` attrs, so the generator
//! strips them from the expected JSON (removing attrs objects that become
//! empty) and `strip_block_ids` below applies the same transform to the Rust
//! output.
//!
//! content_parse.rs is pub(crate) in the library, so it is compiled directly
//! into this test crate via #[path] (it only depends on external crates).

#[path = "../src/crdt_engine/content_parse.rs"]
mod content_parse;

use serde_json::{json, Value};
use std::fs;
use std::path::{Path, PathBuf};

fn fixtures_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("content_parse")
}

/// Mirror of stripBlockIds in the fixture generator: remove `data-block-id`
/// from every attrs object, drop attrs objects that become empty, recurse.
fn strip_block_ids(value: &mut Value) {
    match value {
        Value::Array(items) => {
            for item in items {
                strip_block_ids(item);
            }
        }
        Value::Object(map) => {
            let attrs_now_empty = match map.get_mut("attrs") {
                Some(Value::Object(attrs)) => {
                    attrs.remove("data-block-id");
                    attrs.is_empty()
                }
                _ => false,
            };
            if attrs_now_empty {
                map.remove("attrs");
            }
            for (_, child) in map.iter_mut() {
                strip_block_ids(child);
            }
        }
        _ => {}
    }
}

fn run_case(dir: &Path) {
    let name = dir.file_name().unwrap().to_string_lossy().to_string();
    let input = fs::read_to_string(dir.join("input.txt"))
        .unwrap_or_else(|e| panic!("{name}: read input.txt: {e}"));
    let format_raw = fs::read_to_string(dir.join("format.txt"))
        .unwrap_or_else(|e| panic!("{name}: read format.txt: {e}"));
    let format = format_raw.trim();
    let expected: Value = serde_json::from_str(
        &fs::read_to_string(dir.join("expected.json"))
            .unwrap_or_else(|e| panic!("{name}: read expected.json: {e}")),
    )
    .unwrap_or_else(|e| panic!("{name}: parse expected.json: {e}"));

    let parsed = content_parse::parse_write_content(&input, Some(format))
        .unwrap_or_else(|e| panic!("{name}: parse_write_content failed: {e}"));
    let mut actual = json!({
        "tiptapJson": parsed.tiptap_json,
        "derivedTitle": parsed.derived_title,
        "sourceFormat": parsed.source_format,
        "warnings": parsed.warnings,
    });
    strip_block_ids(&mut actual["tiptapJson"]);

    assert_eq!(
        actual,
        expected,
        "fixture `{name}` diverged\nactual:\n{}\nexpected:\n{}",
        serde_json::to_string_pretty(&actual).unwrap(),
        serde_json::to_string_pretty(&expected).unwrap(),
    );

    // `format: "auto"` must behave identically to an omitted format
    // (writeContentFormat maps unknown values to auto).
    if format == "auto" {
        let parsed_none = content_parse::parse_write_content(&input, None)
            .unwrap_or_else(|e| panic!("{name}: parse_write_content(None) failed: {e}"));
        let mut actual_none = json!({
            "tiptapJson": parsed_none.tiptap_json,
            "derivedTitle": parsed_none.derived_title,
            "sourceFormat": parsed_none.source_format,
            "warnings": parsed_none.warnings,
        });
        strip_block_ids(&mut actual_none["tiptapJson"]);
        assert_eq!(
            actual_none, expected,
            "fixture `{name}` (format=None) diverged"
        );
    }
}

#[test]
fn content_parse_matches_ts_fixtures() {
    let root = fixtures_root();
    let mut dirs: Vec<PathBuf> = fs::read_dir(&root)
        .unwrap_or_else(|e| panic!("missing fixtures at {}: {e}", root.display()))
        .filter_map(|entry| entry.ok().map(|e| e.path()))
        .filter(|path| path.is_dir())
        .collect();
    dirs.sort();
    assert!(
        !dirs.is_empty(),
        "no content_parse fixtures found; run the generator (see module docs)"
    );
    for dir in &dirs {
        run_case(dir);
    }
    println!("verified {} fixtures", dirs.len());
}

/// Block ids exist before normalization strips them for comparison: every
/// block-level node gets a `data-block-id` matching `block-<8 hex chars>`.
#[test]
fn assigns_block_ids() {
    let parsed =
        content_parse::parse_write_content("# Title\n\nBody text.", Some("markdown")).unwrap();
    let content = parsed.tiptap_json["content"].as_array().unwrap();
    assert_eq!(content.len(), 2);
    for node in content {
        let id = node["attrs"]["data-block-id"].as_str().unwrap();
        assert!(id.starts_with("block-"), "unexpected id {id}");
        assert_eq!(id.len(), "block-".len() + 8);
    }
}
