//! Focused tests for the pure core of src/crdt_engine/import_vault_ops.rs:
//! zip parsing (obsidian/notion/roam), title-lookup-key normalization,
//! fnv1aPath determinism, and the import-plan resolution layer — all checked
//! against fixtures generated by the ACTUAL frontend implementation
//! (frontend/scripts/generate-vault-fixtures.test.mts), which builds the same
//! stored zips the parity harness builds.
//!
//! The module is compiled into this test crate via #[path]; the crate-level
//! infrastructure the async handler references (ledger, pending uploads,
//! document/workspace ops) is satisfied by thin shims below, exactly like
//! tests/block_ops.rs. The handler itself needs an AppHandle and is exercised
//! end-to-end by the cell integration suite / parity harness, not this file.

#![allow(dead_code)]

mod app_runtime {
    #[cfg(feature = "desktop")]
    pub(crate) type AppHandle = tauri::AppHandle<tauri::Wry>;
    #[cfg(not(feature = "desktop"))]
    #[derive(Clone)]
    pub(crate) struct AppHandle;
}

mod crdt_queue {
    #[derive(Debug, Clone)]
    pub(crate) struct CrdtOperation {
        pub(crate) operation_id: String,
        pub(crate) kind: String,
        pub(crate) graph_id: String,
        pub(crate) document_id: Option<String>,
        pub(crate) payload: serde_json::Value,
        pub(crate) enqueue_timestamp: String,
    }
}

mod executor {
    #[derive(Debug)]
    pub(crate) enum ApplyOperationError {
        Terminal(String),
        RetryableAfterHotCommit(String),
    }

    pub(crate) type ApplyOperationResult<T> = Result<T, ApplyOperationError>;

    impl ApplyOperationError {
        pub(crate) fn terminal(error: impl Into<String>) -> Self {
            Self::Terminal(error.into())
        }

        pub(crate) fn retryable_after_hot_commit(error: impl Into<String>) -> Self {
            Self::RetryableAfterHotCommit(error.into())
        }

        pub(crate) fn into_message(self) -> String {
            match self {
                Self::Terminal(error) | Self::RetryableAfterHotCommit(error) => error,
            }
        }
    }

    impl From<String> for ApplyOperationError {
        fn from(error: String) -> Self {
            Self::Terminal(error)
        }
    }
}

mod cell_durability {
    pub(crate) struct ImportGuard;
    pub(crate) fn import_guard() -> ImportGuard {
        ImportGuard
    }
}

mod graph_paths {
    pub(crate) fn existing_graph_dir(
        _app: &crate::app_runtime::AppHandle,
        _graph_id: &str,
    ) -> Result<std::path::PathBuf, String> {
        Err("graph_paths is not available in standalone import_vault_ops tests".into())
    }
}

mod ydoc_paths {
    use std::path::{Path, PathBuf};
    pub(crate) fn document_ydoc_dir(graph_dir: &Path, document_id: &str) -> PathBuf {
        graph_dir.join("ydocs/documents").join(document_id)
    }
}

mod operation_completion_ledger {
    #[derive(Debug, Clone)]
    pub(crate) struct OperationCompletionEntry {
        pub(crate) schema_version: u32,
        pub(crate) operation_id: String,
        pub(crate) kind: String,
        pub(crate) graph_id: Option<String>,
        pub(crate) completed_at: String,
        pub(crate) payload_hash: Option<String>,
        pub(crate) result: Option<serde_json::Value>,
    }
    pub(crate) fn completion_entry_for(
        _app: &crate::app_runtime::AppHandle,
        _operation_id: &str,
    ) -> Result<Option<OperationCompletionEntry>, String> {
        Ok(None)
    }
    pub(crate) fn append_completion_entry(
        _app: &crate::app_runtime::AppHandle,
        _entry: OperationCompletionEntry,
    ) -> Result<(), String> {
        Err("ledger is not available in standalone import_vault_ops tests".into())
    }
}

mod pending_upload_service {
    pub(crate) struct PendingUploadFileInput {
        pub(crate) graph_id: Option<String>,
        pub(crate) pending_path: String,
    }
    pub(crate) struct PendingUploadFileRecord {
        pub(crate) graph_id: Option<String>,
        pub(crate) pending_path: String,
        pub(crate) size_bytes: usize,
        pub(crate) data_base64: String,
    }
    pub(crate) fn read_pending_upload_file(
        _app: crate::app_runtime::AppHandle,
        _input: PendingUploadFileInput,
    ) -> Result<PendingUploadFileRecord, String> {
        Err("pending uploads are not available in standalone import_vault_ops tests".into())
    }
    pub(crate) fn cleanup_pending_upload(
        _app: crate::app_runtime::AppHandle,
        _input: PendingUploadFileInput,
    ) -> Result<(), String> {
        Ok(())
    }
}

mod document_ops {
    pub(crate) async fn document_write(
        _app: &crate::app_runtime::AppHandle,
        _operation: &crate::crdt_queue::CrdtOperation,
    ) -> Result<serde_json::Value, String> {
        Err("document_ops is not available in standalone import_vault_ops tests".into())
    }

    pub(crate) async fn document_write_classified(
        _app: &crate::app_runtime::AppHandle,
        _operation: &crate::crdt_queue::CrdtOperation,
    ) -> crate::executor::ApplyOperationResult<serde_json::Value> {
        Err(crate::executor::ApplyOperationError::Terminal(
            "document_ops is not available in standalone import_vault_ops tests".into(),
        ))
    }
}

mod workspace_ops {
    pub(crate) async fn apply(
        _app: &crate::app_runtime::AppHandle,
        _operation: &crate::crdt_queue::CrdtOperation,
    ) -> Result<serde_json::Value, String> {
        Err("workspace_ops is not available in standalone import_vault_ops tests".into())
    }

    pub(crate) async fn apply_classified(
        _app: &crate::app_runtime::AppHandle,
        _operation: &crate::crdt_queue::CrdtOperation,
    ) -> crate::executor::ApplyOperationResult<serde_json::Value> {
        Err(crate::executor::ApplyOperationError::Terminal(
            "workspace_ops is not available in standalone import_vault_ops tests".into(),
        ))
    }
}

#[path = "../src/crdt_engine/import_vault_ops.rs"]
mod import_vault_ops;

use import_vault_ops::{
    archive_import_source, archive_title_lookup_keys, build_vault_import_plan,
    create_import_result, fnv1a_path, import_result_envelope, parse_archive_import,
    resolve_archive_title, unresolved_links_warning, ArchiveImportParseResult, ArchiveImportSource,
};
use serde_json::{json, Value};
use std::collections::HashMap;
use std::path::PathBuf;

// ---------------------------------------------------------------------------
// Fixture helpers
// ---------------------------------------------------------------------------

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/vault_import")
}

fn fixture_bytes(name: &str) -> Vec<u8> {
    let path = fixture_dir().join(name);
    std::fs::read(&path).unwrap_or_else(|error| {
        panic!(
            "read {} failed ({error}); regenerate with `pnpm exec vitest run --config scripts/vitest.fixture.config.ts scripts/generate-vault-fixtures.test.mts` from frontend/",
            path.display()
        )
    })
}

fn fixture_json(name: &str) -> Value {
    serde_json::from_slice(&fixture_bytes(name)).expect("fixture JSON parses")
}

fn source_for(name: &str) -> ArchiveImportSource {
    archive_import_source(Some(&json!(name))).expect("known source")
}

/// Serialize the Rust parse result in the generator's normalized shape.
fn parse_result_json(result: &ArchiveImportParseResult) -> Value {
    json!({
        "documents": result
            .documents
            .iter()
            .map(|document| {
                json!({
                    "title": document.title,
                    "markdown": document.markdown,
                    "folderPath": document.folder_path,
                    "sourceFilename": document.source_filename,
                })
            })
            .collect::<Vec<_>>(),
        "wikilinks": result
            .wikilinks
            .iter()
            .map(|link| {
                json!({
                    "sourceTitle": link.source_title,
                    "targetTitle": link.target_title,
                    "displayText": link.display_text,
                    "sourceContext": link.source_context,
                    "isTag": link.is_tag,
                })
            })
            .collect::<Vec<_>>(),
        "warnings": result.warnings,
    })
}

fn parsed_fixture(name: &str) -> ArchiveImportParseResult {
    // Fixture names are `<source>` or `<source>-edge`.
    let base = name.split('-').next().expect("fixture name");
    let zip = fixture_bytes(&format!("{name}.zip"));
    parse_archive_import(source_for(base), &zip)
}

/// Compare the Rust parse of `<source>.zip` against the TS-generated
/// `<source>.parsed.json`, byte-exact field by field.
fn assert_parse_parity(source: &str) {
    let actual = parse_result_json(&parsed_fixture(source));
    let expected = fixture_json(&format!("{source}.parsed.json"));
    assert_eq!(
        actual, expected,
        "{source}: Rust parse result must match the frontend parser output"
    );
}

struct PlanCounts {
    documents_created: usize,
    folders_created: usize,
    wires_created: usize,
    tags_created: usize,
    unresolved_links: usize,
}

fn plan_counts(source: &str) -> PlanCounts {
    let parsed = parsed_fixture(source);
    let expected = fixture_json(&format!("{source}.expected.json"));
    let folder_name = expected["folderName"].as_str().expect("folderName");
    let plan = build_vault_import_plan(
        &parsed,
        Some(folder_name),
        "op-vault-fixture",
        1_760_000_000_000.0,
    )
    .expect("plan builds");
    let counts = PlanCounts {
        documents_created: plan.assignments.len(),
        folders_created: plan.folders.len(),
        wires_created: plan.wires.len(),
        tags_created: plan.tags_created,
        unresolved_links: plan.unresolved.len(),
    };
    assert_eq!(
        counts.documents_created,
        expected["documentsCreated"].as_u64().unwrap() as usize,
        "{source}: documentsCreated"
    );
    assert_eq!(
        counts.folders_created,
        expected["foldersCreated"].as_u64().unwrap() as usize,
        "{source}: foldersCreated"
    );
    assert_eq!(
        counts.wires_created,
        expected["wiresCreated"].as_u64().unwrap() as usize,
        "{source}: wiresCreated"
    );
    assert_eq!(
        counts.tags_created,
        expected["tagsCreated"].as_u64().unwrap() as usize,
        "{source}: tagsCreated"
    );
    assert_eq!(
        counts.unresolved_links,
        expected["unresolvedLinks"].as_u64().unwrap() as usize,
        "{source}: unresolvedLinks"
    );
    counts
}

// ---------------------------------------------------------------------------
// Parser parity against the TS-generated fixtures
// ---------------------------------------------------------------------------

#[test]
fn obsidian_parse_matches_frontend_parser() {
    assert_parse_parity("obsidian");
}

#[test]
fn notion_parse_matches_frontend_parser() {
    assert_parse_parity("notion");
}

#[test]
fn roam_parse_matches_frontend_parser() {
    assert_parse_parity("roam");
}

#[test]
fn edge_fixtures_parse_and_plan_match_frontend() {
    // Edge archives pin the subtler semantics: quoted frontmatter titles,
    // block-style `tags:` lists (greedy \s* captures '- alpha'), code-span
    // masking vs. unmasked hashtag replacement, image embeds, empty display
    // text, Notion percent-decoding (incl. malformed), CSV quoting/pipes,
    // Roam TODO/DONE + block refs (consumed before embeds), nested
    // wikilinks, attribute lines, V8 date rollover (Feb 30 → March), and the
    // multiple-JSON-files warning.
    for name in ["obsidian-edge", "notion-edge", "roam-edge"] {
        assert_parse_parity(name);
        plan_counts(name);
    }
}

#[test]
fn invalid_zip_yields_the_verbatim_warning() {
    for source in ["obsidian", "notion", "roam"] {
        let result = parse_archive_import(source_for(source), b"not zip");
        assert!(result.documents.is_empty());
        assert!(result.wikilinks.is_empty());
        assert_eq!(result.warnings, vec!["Invalid ZIP file".to_string()]);
    }
}

#[test]
fn empty_zip_reports_no_markdown_files() {
    // A structurally valid zip with no entries (EOCD record only).
    let mut empty = vec![0x50, 0x4b, 0x05, 0x06];
    empty.extend_from_slice(&[0u8; 18]);
    let result = parse_archive_import(ArchiveImportSource::Obsidian, &empty);
    assert_eq!(
        result.warnings,
        vec!["No markdown files found in ZIP".to_string()]
    );
    let result = parse_archive_import(ArchiveImportSource::Roam, &empty);
    assert_eq!(
        result.warnings,
        vec!["No JSON file found in ZIP".to_string()]
    );
}

// ---------------------------------------------------------------------------
// Resolution layer: plan counts match the parity harness's asserted numbers
// ---------------------------------------------------------------------------

#[test]
fn obsidian_plan_matches_harness_numbers() {
    let counts = plan_counts("obsidian");
    // check-loopback-surface.mjs: documentsCreated 4, tagsCreated 2,
    // unresolvedLinks 1, wiresCreated >= 3.
    assert_eq!(counts.documents_created, 4);
    assert_eq!(counts.tags_created, 2);
    assert_eq!(counts.unresolved_links, 1);
    assert!(counts.wires_created >= 3);
}

#[test]
fn notion_plan_matches_harness_numbers() {
    let counts = plan_counts("notion");
    // check-loopback-surface.mjs: documentsCreated 3, wiresCreated 1,
    // unresolvedLinks 0.
    assert_eq!(counts.documents_created, 3);
    assert_eq!(counts.wires_created, 1);
    assert_eq!(counts.unresolved_links, 0);
}

#[test]
fn roam_plan_matches_harness_numbers() {
    let counts = plan_counts("roam");
    // check-loopback-surface.mjs: documentsCreated 3, tagsCreated 1,
    // wiresCreated >= 2, unresolvedLinks 0.
    assert_eq!(counts.documents_created, 3);
    assert_eq!(counts.tags_created, 1);
    assert!(counts.wires_created >= 2);
    assert_eq!(counts.unresolved_links, 0);
}

#[test]
fn obsidian_plan_details_are_deterministic_and_faithful() {
    let parsed = parsed_fixture("obsidian");
    let plan = build_vault_import_plan(
        &parsed,
        Some("Parity Obsidian fixture"),
        "op-vault-fixture",
        1_760_000_000_000.0,
    )
    .expect("plan builds");

    // Folders: root, root/Projects, root/Tags — ids derived via fnv1aPath.
    let folder_names: Vec<&str> = plan.folders.iter().map(|f| f.name.as_str()).collect();
    assert_eq!(
        folder_names,
        vec!["Parity Obsidian fixture", "Projects", "Tags"]
    );
    for folder in &plan.folders {
        assert!(folder.folder_id.starts_with("op-vault-fixture-folder-"));
    }
    // Projects is parented under the root folder.
    assert_eq!(
        plan.folders[1].parent_id.as_deref(),
        Some(plan.folders[0].folder_id.as_str())
    );
    assert_eq!(
        plan.folders[2].parent_id.as_deref(),
        Some(plan.folders[0].folder_id.as_str())
    );

    // Deterministic document ids from sourceFilename / tag title.
    for assignment in &plan.assignments {
        assert!(assignment.document_id.starts_with("op-vault-fixture-doc-"));
    }
    let expected_source_id = format!(
        "op-vault-fixture-doc-{}",
        fnv1a_path("Projects/Archive Source fixture.md").unwrap()
    );
    assert_eq!(plan.assignments[0].document_id, expected_source_id);
    // Tag hubs land in the Tags folder, sorted, with `# tag` bodies.
    let tag_hubs: Vec<_> = plan.assignments.iter().filter(|a| a.is_tag_hub).collect();
    assert_eq!(tag_hubs.len(), 2);
    assert_eq!(tag_hubs[0].document.title, "archive-tag-fixture");
    assert_eq!(tag_hubs[1].document.title, "loose-tag-fixture");
    assert_eq!(tag_hubs[0].document.markdown, "# archive-tag-fixture");
    assert_eq!(
        tag_hubs[0].parent_id.as_deref(),
        Some(plan.folders[2].folder_id.as_str())
    );

    // Wires: the wikilink wire plus two exemplifies tag wires.
    let predicates: Vec<&str> = plan.wires.iter().map(|w| w.predicate).collect();
    assert_eq!(predicates, vec!["isWiredTo", "exemplifies", "exemplifies"]);
    for wire in &plan.wires {
        assert!(wire.wire_id.starts_with("op-vault-fixture-w-"));
        assert_eq!(wire.source_document_id, expected_source_id);
    }
    // Block candidates follow TS order: displayText, targetTitle, sourceContext.
    assert_eq!(
        plan.wires[0].block_candidates,
        vec![
            "target display".to_string(),
            "Archive Target fixture".to_string(),
            "See [[Archive Target fixture|target display]] and #loose-tag-fixture.".to_string(),
        ]
    );

    // Unresolved: the missing title only.
    assert_eq!(plan.unresolved, vec!["Archive Missing fixture".to_string()]);
    assert_eq!(
        unresolved_links_warning(&plan.unresolved),
        "1 wikilinks could not be resolved: [[Archive Missing fixture]]"
    );
}

#[test]
fn unresolved_warning_truncates_past_ten_titles() {
    let unresolved: Vec<String> = (0..12).map(|i| format!("T{i:02}")).collect();
    let warning = unresolved_links_warning(&unresolved);
    assert_eq!(
        warning,
        "12 wikilinks could not be resolved: [[T00]], [[T01]], [[T02]], [[T03]], [[T04]], [[T05]], [[T06]], [[T07]], [[T08]], [[T09]] ... and 2 more"
    );
}

// ---------------------------------------------------------------------------
// Title lookup keys + fuzzy resolution (TS-generated vectors)
// ---------------------------------------------------------------------------

#[test]
fn title_lookup_keys_match_ts_vectors() {
    let vectors = fixture_json("title-lookup-keys.json");
    for case in vectors.as_array().expect("vector array") {
        let title = case["title"].as_str().unwrap();
        let expected: Vec<String> = case["keys"]
            .as_array()
            .unwrap()
            .iter()
            .map(|key| key.as_str().unwrap().to_string())
            .collect();
        assert_eq!(
            archive_title_lookup_keys(title),
            expected,
            "lookup keys for {title:?}"
        );
    }
}

#[test]
fn fuzzy_title_resolution_crosses_quote_and_dash_variants() {
    let mut map: HashMap<String, String> = HashMap::new();
    for key in archive_title_lookup_keys("Don\u{2019}t Stop \u{2013} Believing") {
        map.entry(key).or_insert_with(|| "doc-1".to_string());
    }
    assert_eq!(
        resolve_archive_title(&map, "don't stop - believing").as_deref(),
        Some("doc-1")
    );
    assert_eq!(
        resolve_archive_title(&map, "[[Don\u{2019}t Stop \u{2013} Believing]]").as_deref(),
        Some("doc-1")
    );
    assert_eq!(resolve_archive_title(&map, "something else"), None);
}

#[test]
fn fnv1a_path_matches_ts_vectors() {
    let vectors = fixture_json("fnv1a.json");
    for case in vectors.as_array().expect("vector array") {
        let path = case["path"].as_str().unwrap();
        let expected = case["hash"].as_str().unwrap();
        assert_eq!(
            fnv1a_path(path).expect("hashable"),
            expected,
            "fnv1aPath({path:?})"
        );
    }
    assert_eq!(
        fnv1a_path("").unwrap_err(),
        "fnv1aPath: path must not be empty"
    );
}

// ---------------------------------------------------------------------------
// Envelope + error strings
// ---------------------------------------------------------------------------

#[test]
fn envelope_carries_dual_snake_and_camel_keys() {
    let mut result = create_import_result();
    result.documents_created = 4;
    result.folders_created = 3;
    result.wires_created = 3;
    result.tags_created = 2;
    result.unresolved_links = 1;
    result.document_ids = vec!["d1".to_string(), "d2".to_string()];
    result.warnings = vec!["w".to_string()];
    let envelope = import_result_envelope(&result);
    assert_eq!(envelope["status"], "complete");
    for (snake, camel) in [
        ("documents_created", "documentsCreated"),
        ("folders_created", "foldersCreated"),
        ("wires_created", "wiresCreated"),
        ("tags_created", "tagsCreated"),
        ("unresolved_links", "unresolvedLinks"),
        ("document_ids", "documentIds"),
    ] {
        assert_eq!(envelope[snake], envelope[camel], "{snake} mirrors {camel}");
    }
    assert_eq!(envelope["documentsCreated"], 4);
    assert_eq!(envelope["documentIds"], json!(["d1", "d2"]));
    assert_eq!(envelope["warnings"], json!(["w"]));
    assert_eq!(envelope["errors"], json!([]));
}

#[test]
fn archive_import_source_errors_are_verbatim() {
    assert!(matches!(
        archive_import_source(Some(&json!("Obsidian"))),
        Ok(ArchiveImportSource::Obsidian)
    ));
    assert!(matches!(
        archive_import_source(Some(&json!("  ROAM  "))),
        Ok(ArchiveImportSource::Roam)
    ));
    assert_eq!(
        archive_import_source(Some(&json!("evernote"))).unwrap_err(),
        "unsupported archive import source: evernote"
    );
    assert_eq!(
        archive_import_source(None).unwrap_err(),
        "unsupported archive import source: missing"
    );
    assert_eq!(
        archive_import_source(Some(&Value::Null)).unwrap_err(),
        "unsupported archive import source: missing"
    );
}

#[test]
fn missing_path_key_error_is_verbatim() {
    use import_vault_ops::{ArchiveImportedDocument, ArchiveWikiLink};
    let parsed = ArchiveImportParseResult {
        documents: vec![ArchiveImportedDocument {
            title: String::new(),
            markdown: "body".to_string(),
            folder_path: None,
            source_filename: None,
        }],
        wikilinks: Vec::<ArchiveWikiLink>::new(),
        warnings: Vec::new(),
    };
    assert_eq!(
        build_vault_import_plan(&parsed, None, "op", 0.0).unwrap_err(),
        "import.vault: document has neither sourceFilename nor title; cannot derive deterministic ID"
    );
}
