//! End-to-end fixtures for the pure core of src/crdt_engine/web_clip_ops.rs:
//! parse_local_web_clip(html, url, title_override) checked byte-for-byte
//! (title and assembled markdown, no normalization) against fixtures
//! generated by running the ACTUAL frontend parseLocalWebClip under jsdom
//! (frontend/scripts/generate-webclip-fixtures.test.mts →
//! tests/fixtures/web_clip/).
//!
//! The parser is imported from Garden's real library, while the full handler
//! remains covered by the cell integration suite.

use garden_lib::crdt_engine::web_clip_ops::parse_local_web_clip;
use std::fs;
use std::path::PathBuf;

fn fixtures_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/web_clip")
}

#[test]
fn web_clip_fixtures_match_ts_reference() {
    let root = fixtures_root();
    let mut names: Vec<String> = fs::read_dir(&root)
        .unwrap_or_else(|e| panic!("fixtures missing at {} ({e}); run frontend/scripts/generate-webclip-fixtures.test.mts", root.display()))
        .filter_map(|entry| {
            let entry = entry.expect("readable dir entry");
            entry
                .file_type()
                .expect("file type")
                .is_dir()
                .then(|| entry.file_name().to_string_lossy().into_owned())
        })
        .collect();
    names.sort();
    assert!(
        names.len() >= 6,
        "expected at least 6 web-clip fixtures, found {names:?}"
    );

    for name in names {
        let dir = root.join(&name);
        let html = fs::read_to_string(dir.join("input.html")).expect("input.html");
        let url = fs::read_to_string(dir.join("url.txt")).expect("url.txt");
        let title_override = fs::read_to_string(dir.join("title-override.txt")).ok();
        let expected: serde_json::Value = serde_json::from_str(
            &fs::read_to_string(dir.join("expected.json")).expect("expected.json"),
        )
        .expect("valid expected.json");
        let expected_title = expected["title"].as_str().expect("expected title");
        let expected_markdown = expected["markdown"].as_str().expect("expected markdown");

        let parsed = parse_local_web_clip(&html, &url, title_override.as_deref())
            .unwrap_or_else(|e| panic!("[{name}] parse_local_web_clip failed: {e}"));

        assert_eq!(parsed.title, expected_title, "[{name}] title mismatch");
        assert_eq!(
            parsed.markdown, expected_markdown,
            "[{name}] markdown mismatch"
        );
        assert_eq!(
            parsed.warnings,
            vec![
                "Local web clip used the desktop HTML extractor and Markdown write path."
                    .to_string()
            ],
            "[{name}] warnings mismatch"
        );
    }
}
