//! Port of `parseTipTapWriteContent` from
//! frontend/src/native/artifact-ingest.ts for the headless cell's in-process
//! executor (`document.write` content parsing).
//!
//! Behavior is verified against fixtures generated by running the actual TS
//! function: frontend/scripts/generate-content-parse-fixtures.test.mts →
//! tests/fixtures/content_parse/ → tests/content_parse_fixtures.rs.
//!
//! Faithfulness notes (vs the TS reference):
//! - Markdown is parsed with pulldown-cmark (GFM strikethrough/tasklists/
//!   tables) instead of `marked`; adjacent text/softbreak runs are merged into
//!   a single text node, which matches marked's tokenization for normal prose.
//!   Known divergences (all exotic): backslash-escape sequences produce one
//!   merged text node here but two separate nodes in TS; HTML entities are
//!   decoded by pulldown-cmark but kept literal by marked; footnote
//!   definitions whose content is a single word are treated as link-reference
//!   definitions by both parsers but TS additionally records them as
//!   footnotes; GFM tables are dropped by both (marked emits an unhandled
//!   `table` token, we skip the events).
//! - marked HTML-escapes code-span text (`escape(text, true)`); replicated in
//!   `escape_marked_codespan` so inline code matches the TS byte-for-byte.
//! - HTML content (explicit `format: "html"` or auto-detected) is parsed by
//!   the Rust port of the TS path (prepareHtmlForTipTapImport + TipTap
//!   generateJSON) in html_to_tiptap.rs, verified against fixtures generated
//!   from the real TS pipeline (tests/html_to_tiptap.rs). Raw HTML blocks
//!   embedded in markdown go through the same converter (the TS try branch);
//!   only on converter error do they fall back to the TS catch-branch
//!   behavior (strip markup → paragraph), silently.
//! - `strip_markup` approximates DOMParser `textContent` with a tag stripper
//!   + basic entity decoding; only reachable on fallback paths.
//! - XML parse error *messages* come from roxmltree, not DOMParser, so the
//!   warning text on invalid XML differs (the fallback behavior is the same).

#![allow(dead_code)] // TODO: remove once the executor routes document.write through parse_write_content.

// Declared here (not in crdt_engine/mod.rs) so the #[path] test shims that
// compile content_parse.rs standalone pull the HTML converter along with it.
#[path = "html_to_tiptap.rs"]
pub(crate) mod html_to_tiptap;

use std::collections::HashMap;
use std::sync::LazyLock;

use pulldown_cmark::{CodeBlockKind, Event, HeadingLevel, Options, Parser, Tag, TagEnd};
use regex::Regex;
use serde_json::{json, Map, Value};

pub(crate) struct ParsedWriteContent {
    /// `{type:"doc", content:[...]}` — normalized flat-list TipTap JSON with
    /// `data-block-id` attrs assigned (random, `block-<uuid8>`).
    pub(crate) tiptap_json: Value,
    pub(crate) derived_title: Option<String>,
    /// One of "plain" | "markdown" | "html" | "xml".
    pub(crate) source_format: String,
    pub(crate) warnings: Vec<String>,
}

/// Port of `parseTipTapWriteContent(content, format)`.
///
/// `format` follows `writeContentFormat` in native-local-runtime.ts: only
/// "plain" | "markdown" | "html" | "xml" are honored, anything else
/// (including `None` and "auto") means auto-detection. Like the TS, this
/// never fails — parse errors degrade to plain text with a warning.
pub(crate) fn parse_write_content(
    content: &str,
    format: Option<&str>,
) -> Result<ParsedWriteContent, String> {
    parse_write_content_with_block_id_seed(content, format, None)
}

/// Production CRDT writes use the durable operation id as the fallback block
/// id seed. The frontend parser's random IDs are correct for a fresh edit, but
/// regenerating them during journal replay makes equal content look different
/// and manufactures a second document revision after a completed cold tail.
pub(crate) fn parse_write_content_for_operation(
    content: &str,
    format: Option<&str>,
    operation_id: &str,
) -> Result<ParsedWriteContent, String> {
    parse_write_content_with_block_id_seed(content, format, Some(operation_id))
}

fn parse_write_content_with_block_id_seed(
    content: &str,
    format: Option<&str>,
    block_id_seed: Option<&str>,
) -> Result<ParsedWriteContent, String> {
    let normalized = normalize_newlines(content);
    let trimmed = normalized.trim();
    let mut warnings: Vec<String> = Vec::new();
    let source_format = resolve_write_content_format(trimmed, format);

    let tiptap_json = match source_format {
        "xml" => match tiptap_xml_to_tiptap_json(trimmed) {
            Ok(value) => value,
            Err(error) => {
                warnings.push(format!("Content parse fallback: {error}"));
                text_to_tiptap_json(&strip_markup(&normalized))
            }
        },
        "markdown" => markdown_to_tiptap_json(&normalized),
        "html" => match html_to_tiptap::html_to_tiptap_json(&normalized) {
            // TS: generateJSON(prepareHtmlForTipTapImport(normalized), EXPORT_EXTENSIONS)
            Ok(value) => value,
            Err(error) => {
                // TS catch branch: textToTipTapJson(stripMarkup(normalized))
                warnings.push(format!("Content parse fallback: {error}"));
                text_to_tiptap_json(&strip_markup(&normalized))
            }
        },
        _ => text_to_tiptap_json(&normalized),
    };

    let parsed = normalize_imported_tiptap_json(tiptap_json, block_id_seed);
    let derived_title = extract_title_from_tiptap_json(&parsed);
    Ok(ParsedWriteContent {
        tiptap_json: parsed,
        derived_title,
        source_format: source_format.to_string(),
        warnings,
    })
}

// ---------------------------------------------------------------------------
// Format detection
// ---------------------------------------------------------------------------

static HTML_BLOCK_TAG_RE: LazyLock<Regex> = LazyLock::new(|| {
    Regex::new(r"(?i)^\s*<(?:p|h[1-6]|ul|ol|li|blockquote|pre|table|hr|img|div|section|article)\b")
        .expect("valid regex")
});

static MARKDOWN_HINT_RES: LazyLock<Vec<Regex>> = LazyLock::new(|| {
    [
        r"(?m)^#{1,6}\s+",
        r"(?m)^>\s+",
        r"(?m)^```",
        r"(?m)^[-+*]\s+",
        r"(?m)^\d+\.\s+",
        r"(?m)^[-+*]\s+\[[ xX]\]\s+",
        r"(?s)(^|[^\\])\*\*[^*\n].*?\*\*",
        r"(?s)(^|[^\\])__[^_\n].*?__",
        r"(?s)(^|[^\\])~~[^~\n].*?~~",
        r"`[^`\n]+`",
        r"\[[^\]]+\]\([^)]+\)",
        r"(?m)^(?:---|\*\*\*|___)\s*$",
    ]
    .iter()
    .map(|p| Regex::new(p).expect("valid regex"))
    .collect()
});

fn resolve_write_content_format(trimmed: &str, format: Option<&str>) -> &'static str {
    match format {
        Some("plain") => return "plain",
        Some("markdown") => return "markdown",
        Some("html") => return "html",
        Some("xml") => return "xml",
        _ => {} // 'auto' / unknown / absent → detect
    }
    if trimmed.is_empty() {
        return "plain";
    }
    if trimmed.starts_with('<') {
        if HTML_BLOCK_TAG_RE.is_match(trimmed) {
            return "html";
        }
        return "xml";
    }
    if looks_like_markdown(trimmed) {
        "markdown"
    } else {
        "plain"
    }
}

fn looks_like_markdown(value: &str) -> bool {
    MARKDOWN_HINT_RES.iter().any(|re| re.is_match(value))
}

fn normalize_newlines(value: &str) -> String {
    value.replace("\r\n", "\n").replace('\r', "\n")
}

// ---------------------------------------------------------------------------
// Plain text
// ---------------------------------------------------------------------------

static PARAGRAPH_SPLIT_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"\n{2,}").expect("valid regex"));
static MULTI_SPACE_RE: LazyLock<Regex> = LazyLock::new(|| Regex::new(r"  +").expect("valid regex"));

fn text_to_tiptap_json(text: &str) -> Value {
    let normalized = normalize_newlines(text);
    let paragraphs: Vec<String> = PARAGRAPH_SPLIT_RE
        .split(&normalized)
        .map(|paragraph| {
            let collapsed = paragraph.trim().replace('\n', " ");
            MULTI_SPACE_RE.replace_all(&collapsed, " ").into_owned()
        })
        .filter(|paragraph| !paragraph.is_empty())
        .collect();

    let content: Vec<Value> = if paragraphs.is_empty() {
        vec![json!({"type": "paragraph"})]
    } else {
        paragraphs
            .into_iter()
            .map(|paragraph| json!({"type": "paragraph", "content": [{"type": "text", "text": paragraph}]}))
            .collect()
    };
    json!({"type": "doc", "content": content})
}

/// Approximation of DOMParser('text/html').body.textContent for fallback
/// paths: strips tags, decodes the common entities.
fn strip_markup(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    let mut chars = value.char_indices().peekable();
    while let Some((idx, ch)) = chars.next() {
        if ch == '<' {
            let looks_like_tag = value[idx + 1..]
                .chars()
                .next()
                .map(|c| c.is_ascii_alphabetic() || c == '/' || c == '!' || c == '?')
                .unwrap_or(false);
            if looks_like_tag {
                for (_, c) in chars.by_ref() {
                    if c == '>' {
                        break;
                    }
                }
                continue;
            }
        }
        out.push(ch);
    }
    decode_basic_entities(&out)
}

fn decode_basic_entities(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    let mut rest = value;
    while let Some(pos) = rest.find('&') {
        out.push_str(&rest[..pos]);
        let candidate = &rest[pos..];
        let semi = candidate.find(';').filter(|i| *i <= 10);
        if let Some(semi) = semi {
            let entity = &candidate[1..semi];
            let decoded = match entity {
                "amp" => Some('&'),
                "lt" => Some('<'),
                "gt" => Some('>'),
                "quot" => Some('"'),
                "apos" => Some('\''),
                "nbsp" => Some('\u{a0}'),
                _ => {
                    if let Some(num) = entity.strip_prefix("#x").or(entity.strip_prefix("#X")) {
                        u32::from_str_radix(num, 16).ok().and_then(char::from_u32)
                    } else if let Some(num) = entity.strip_prefix('#') {
                        num.parse::<u32>().ok().and_then(char::from_u32)
                    } else {
                        None
                    }
                }
            };
            match decoded {
                Some(c) => {
                    out.push(c);
                    rest = &candidate[semi + 1..];
                }
                None => {
                    out.push('&');
                    rest = &candidate[1..];
                }
            }
        } else {
            out.push('&');
            rest = &candidate[1..];
        }
    }
    out.push_str(rest);
    out
}

// ---------------------------------------------------------------------------
// Markdown (pulldown-cmark standing in for marked.lexer)
// ---------------------------------------------------------------------------

type MdIter<'a> = pulldown_cmark::OffsetIter<'a>;
type Footnotes = HashMap<String, String>;

// TS: /^\s*---\s*\n([\s\S]*?)\n---\s*\n?/ (anchored at string start)
static FRONTMATTER_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)\A\s*---\s*\n.*?\n---\s*\n?").expect("valid regex"));
// TS: /^\[\^([^\]]+)]:\s*([\s\S]+?)\s*$/ applied to the paragraph's raw text.
static FOOTNOTE_DEF_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"(?s)\A\[\^([^\]]+)\]:\s*(.+?)\s*\z").expect("valid regex"));
// TS: /\[\^([^\]]+)\]/g for inline footnote references.
static FOOTNOTE_REF_RE: LazyLock<Regex> =
    LazyLock::new(|| Regex::new(r"\[\^([^\]]+)\]").expect("valid regex"));

fn md_options() -> Options {
    Options::ENABLE_STRIKETHROUGH | Options::ENABLE_TASKLISTS | Options::ENABLE_TABLES
}

fn strip_markdown_frontmatter(value: &str) -> String {
    if !value.starts_with("---") {
        return value.to_string();
    }
    match FRONTMATTER_RE.find(value) {
        Some(m) => value[m.end()..].trim_start_matches('\n').to_string(),
        None => value.to_string(),
    }
}

fn markdown_to_tiptap_json(markdown: &str) -> Value {
    let content = strip_markdown_frontmatter(&normalize_newlines(markdown));
    let footnotes = collect_markdown_footnotes(&content);
    let mut iter = Parser::new_ext(&content, md_options()).into_offset_iter();
    let blocks = md_blocks(&mut iter, &content, &footnotes, None);
    json!({"type": "doc", "content": blocks})
}

/// Port of collectMarkdownFootnotes: scans top-level paragraphs whose raw
/// source matches the footnote-definition pattern. (The TS also collects
/// marked `def` tokens with a `^` tag — single-word definitions — which
/// pulldown-cmark consumes as link-reference definitions; see module notes.)
fn collect_markdown_footnotes(content: &str) -> Footnotes {
    let mut footnotes = Footnotes::new();
    let mut depth: usize = 0;
    for (event, range) in Parser::new_ext(content, md_options()).into_offset_iter() {
        match event {
            Event::Start(Tag::Paragraph) if depth == 0 => {
                if let Some(captures) = FOOTNOTE_DEF_RE.captures(content[range].trim_end()) {
                    footnotes.insert(captures[1].to_string(), captures[2].to_string());
                }
                depth += 1;
            }
            Event::Start(_) => depth += 1,
            Event::End(_) => depth = depth.saturating_sub(1),
            _ => {}
        }
    }
    footnotes
}

fn md_blocks(
    iter: &mut MdIter,
    src: &str,
    footnotes: &Footnotes,
    until: Option<TagEnd>,
) -> Vec<Value> {
    let mut out: Vec<Value> = Vec::new();
    while let Some((event, range)) = iter.next() {
        match event {
            Event::End(tag) => {
                if Some(tag) == until {
                    break;
                }
            }
            Event::Rule => out.push(json!({"type": "horizontalRule"})),
            Event::Html(html) => out.extend(html_markdown_block_to_nodes(&html)),
            Event::Start(tag) => {
                let end = tag.to_end();
                match tag {
                    Tag::Paragraph => {
                        let is_footnote_def =
                            FOOTNOTE_DEF_RE.is_match(src[range.clone()].trim_end());
                        let inlines = md_inlines(iter, src, &[], footnotes, TagEnd::Paragraph);
                        if !is_footnote_def {
                            out.push(json!({"type": "paragraph", "content": inlines}));
                        }
                    }
                    Tag::Heading { level, .. } => {
                        let inlines = md_inlines(iter, src, &[], footnotes, TagEnd::Heading(level));
                        out.push(json!({
                            "type": "heading",
                            "attrs": {"level": heading_level_number(level)},
                            "content": inlines,
                        }));
                    }
                    Tag::CodeBlock(kind) => out.push(md_code_block(iter, kind)),
                    Tag::BlockQuote(_) => {
                        let children = md_blocks(iter, src, footnotes, Some(end));
                        out.push(json!({"type": "blockquote", "content": children}));
                    }
                    Tag::List(start) => {
                        out.extend(md_list(iter, src, footnotes, start.is_some(), 0.0));
                    }
                    Tag::HtmlBlock => {
                        let html = collect_html(iter);
                        out.extend(html_markdown_block_to_nodes(&html));
                    }
                    // marked emits a `table` token the TS does not handle
                    // (it falls into the default branch and yields []).
                    Tag::Table(_) => skip_until(iter, TagEnd::Table),
                    other => skip_until(iter, other.to_end()),
                }
            }
            _ => {} // stray inline events at block level: ignore
        }
    }
    out
}

fn heading_level_number(level: HeadingLevel) -> i64 {
    match level {
        HeadingLevel::H1 => 1,
        HeadingLevel::H2 => 2,
        HeadingLevel::H3 => 3,
        HeadingLevel::H4 => 4,
        HeadingLevel::H5 => 5,
        HeadingLevel::H6 => 6,
    }
}

fn md_code_block(iter: &mut MdIter, kind: CodeBlockKind) -> Value {
    let mut text = String::new();
    let mut depth: usize = 0;
    while let Some((event, _)) = iter.next() {
        match event {
            Event::Text(t) => text.push_str(&t),
            Event::Start(_) => depth += 1,
            Event::End(TagEnd::CodeBlock) if depth == 0 => break,
            Event::End(_) => depth = depth.saturating_sub(1),
            _ => {}
        }
    }
    let language = match &kind {
        // marked: token.lang = full info string (truthiness on the whole
        // string), attrs.language = first /\s+/-split segment.
        CodeBlockKind::Fenced(info) if !info.is_empty() => Some(
            info.split(|c: char| c.is_whitespace())
                .next()
                .unwrap_or("")
                .to_string(),
        ),
        _ => None,
    };
    // marked strips the trailing newline from fenced code text (and all
    // trailing newlines from indented code).
    let text = match kind {
        CodeBlockKind::Fenced(_) => text.strip_suffix('\n').unwrap_or(&text).to_string(),
        CodeBlockKind::Indented => text.trim_end_matches('\n').to_string(),
    };

    let mut node = Map::new();
    node.insert("type".into(), json!("codeBlock"));
    if let Some(language) = language {
        node.insert("attrs".into(), json!({"language": language}));
    }
    if !text.is_empty() {
        node.insert("content".into(), json!([{"type": "text", "text": text}]));
    }
    Value::Object(node)
}

fn md_list(
    iter: &mut MdIter,
    src: &str,
    footnotes: &Footnotes,
    ordered: bool,
    indent: f64,
) -> Vec<Value> {
    let list_type = if ordered { "ordered" } else { "bullet" };
    let mut out: Vec<Value> = Vec::new();
    while let Some((event, _)) = iter.next() {
        match event {
            Event::Start(Tag::Item) => {
                out.extend(md_list_item(iter, src, footnotes, list_type, indent));
            }
            Event::End(TagEnd::List(_)) => break,
            _ => {}
        }
    }
    out
}

/// Port of flattenMarkdownListItem: garden's FLAT list model. Emits the item
/// as a standalone `listItem` node (attrs listType/indent[/checked]) whose
/// content is a single paragraph (all inline content merged) plus any direct
/// blocks, followed by the items of nested lists at indent + 1.
fn md_list_item(
    iter: &mut MdIter,
    src: &str,
    footnotes: &Footnotes,
    list_type: &str,
    indent: f64,
) -> Vec<Value> {
    let mut task = false;
    let mut checked = false;
    let mut inline: Vec<Value> = Vec::new();
    let mut direct_blocks: Vec<Value> = Vec::new();
    let mut nested: Vec<Value> = Vec::new();
    let mut buf = String::new();

    while let Some((event, _range)) = iter.next() {
        match event {
            Event::End(TagEnd::Item) => break,
            Event::TaskListMarker(value) => {
                task = true;
                checked = value;
            }
            Event::Start(Tag::List(start)) => {
                flush_text(&mut buf, &[], &mut inline);
                nested.extend(md_list(iter, src, footnotes, start.is_some(), indent + 1.0));
            }
            Event::Start(Tag::Paragraph) => {
                flush_text(&mut buf, &[], &mut inline);
                inline.extend(md_inlines(iter, src, &[], footnotes, TagEnd::Paragraph));
            }
            Event::Start(Tag::Heading { level, .. }) => {
                flush_text(&mut buf, &[], &mut inline);
                let inlines = md_inlines(iter, src, &[], footnotes, TagEnd::Heading(level));
                direct_blocks.push(json!({
                    "type": "heading",
                    "attrs": {"level": heading_level_number(level)},
                    "content": inlines,
                }));
            }
            Event::Start(Tag::CodeBlock(kind)) => {
                flush_text(&mut buf, &[], &mut inline);
                direct_blocks.push(md_code_block(iter, kind));
            }
            Event::Start(Tag::BlockQuote(_)) => {
                flush_text(&mut buf, &[], &mut inline);
                let children = md_blocks(iter, src, footnotes, Some(TagEnd::BlockQuote(None)));
                direct_blocks.push(json!({"type": "blockquote", "content": children}));
            }
            Event::Rule => {
                flush_text(&mut buf, &[], &mut inline);
                direct_blocks.push(json!({"type": "horizontalRule"}));
            }
            Event::Start(Tag::HtmlBlock) => {
                flush_text(&mut buf, &[], &mut inline);
                let html = collect_html(iter);
                direct_blocks.extend(html_markdown_block_to_nodes(&html));
            }
            other => handle_inline_event(other, iter, src, footnotes, &[], &mut buf, &mut inline),
        }
    }
    flush_text(&mut buf, &[], &mut inline);
    let inline = split_footnote_refs(inline, footnotes);

    let paragraph = if inline.is_empty() {
        json!({"type": "paragraph"})
    } else {
        json!({"type": "paragraph", "content": inline})
    };

    let effective_list_type = if task { "task" } else { list_type };
    let mut attrs = Map::new();
    attrs.insert("listType".into(), json!(effective_list_type));
    attrs.insert("indent".into(), number_to_json(indent));
    if effective_list_type == "task" {
        attrs.insert("checked".into(), json!(checked));
    }

    let mut content = vec![paragraph];
    content.append(&mut direct_blocks);

    let mut out = vec![json!({"type": "listItem", "attrs": attrs, "content": content})];
    out.append(&mut nested);
    out
}

fn md_inlines(
    iter: &mut MdIter,
    src: &str,
    marks: &[Value],
    footnotes: &Footnotes,
    until: TagEnd,
) -> Vec<Value> {
    let mut out: Vec<Value> = Vec::new();
    let mut buf = String::new();
    while let Some((event, _)) = iter.next() {
        if let Event::End(tag) = &event {
            if *tag == until {
                break;
            }
        }
        handle_inline_event(event, iter, src, footnotes, marks, &mut buf, &mut out);
    }
    flush_text(&mut buf, marks, &mut out);
    split_footnote_refs(out, footnotes)
}

fn handle_inline_event(
    event: Event,
    iter: &mut MdIter,
    src: &str,
    footnotes: &Footnotes,
    marks: &[Value],
    buf: &mut String,
    out: &mut Vec<Value>,
) {
    match event {
        Event::Text(text) => buf.push_str(&text),
        Event::SoftBreak => buf.push('\n'),
        Event::HardBreak => {
            flush_text(buf, marks, out);
            out.push(json!({"type": "hardBreak"}));
        }
        Event::Code(text) => {
            flush_text(buf, marks, out);
            let mut next = marks.to_vec();
            next.push(json!({"type": "code"}));
            push_text_node(out, &escape_marked_codespan(&text), &next);
        }
        Event::InlineHtml(html) | Event::Html(html) => {
            // TS: inline html tokens become markup-stripped text nodes.
            flush_text(buf, marks, out);
            let stripped = strip_markup(&html);
            if !stripped.is_empty() {
                push_text_node(out, &stripped, marks);
            }
        }
        Event::Start(tag) => {
            let end = tag.to_end();
            match tag {
                Tag::Strong => {
                    flush_text(buf, marks, out);
                    let next = with_mark(marks, "bold", None);
                    out.extend(md_inlines(iter, src, &next, footnotes, end));
                }
                Tag::Emphasis => {
                    flush_text(buf, marks, out);
                    let next = with_mark(marks, "italic", None);
                    out.extend(md_inlines(iter, src, &next, footnotes, end));
                }
                Tag::Strikethrough => {
                    flush_text(buf, marks, out);
                    let next = with_mark(marks, "strike", None);
                    out.extend(md_inlines(iter, src, &next, footnotes, end));
                }
                Tag::Link {
                    dest_url, title, ..
                } => {
                    flush_text(buf, marks, out);
                    let mut attrs = Map::new();
                    attrs.insert("href".into(), json!(dest_url.as_ref()));
                    if !title.is_empty() {
                        attrs.insert("title".into(), json!(title.as_ref()));
                    }
                    let next = with_mark(marks, "link", Some(attrs));
                    out.extend(md_inlines(iter, src, &next, footnotes, end));
                }
                Tag::Image { .. } => {
                    // TS default branch: image token → its alt text.
                    flush_text(buf, marks, out);
                    let alt = collect_image_alt(iter);
                    if !alt.is_empty() {
                        push_text_node(out, &alt, marks);
                    }
                }
                other => skip_until(iter, other.to_end()),
            }
        }
        _ => {}
    }
}

fn with_mark(marks: &[Value], mark_type: &str, attrs: Option<Map<String, Value>>) -> Vec<Value> {
    let mut next = marks.to_vec();
    next.push(match attrs {
        Some(attrs) => json!({"type": mark_type, "attrs": attrs}),
        None => json!({"type": mark_type}),
    });
    next
}

fn flush_text(buf: &mut String, marks: &[Value], out: &mut Vec<Value>) {
    if buf.is_empty() {
        return;
    }
    let text = std::mem::take(buf);
    push_text_node(out, &text, marks);
}

fn push_text_node(out: &mut Vec<Value>, text: &str, marks: &[Value]) {
    let mut node = Map::new();
    node.insert("type".into(), json!("text"));
    node.insert("text".into(), json!(text));
    if !marks.is_empty() {
        node.insert("marks".into(), json!(marks));
    }
    out.push(Value::Object(node));
}

/// Port of markdownTextToTipTapNodes' footnote splitting: `[^key]` inside any
/// text node (including code spans and link text) becomes a footnote atom.
fn split_footnote_refs(nodes: Vec<Value>, footnotes: &Footnotes) -> Vec<Value> {
    let mut out: Vec<Value> = Vec::new();
    for node in nodes {
        let is_text = node.get("type").and_then(Value::as_str) == Some("text");
        if !is_text {
            out.push(node);
            continue;
        }
        let text = node
            .get("text")
            .and_then(Value::as_str)
            .unwrap_or_default()
            .to_string();
        if !FOOTNOTE_REF_RE.is_match(&text) {
            out.push(node);
            continue;
        }
        let marks = node.get("marks").cloned();
        let push_segment = |segment: &str, out: &mut Vec<Value>| {
            if segment.is_empty() {
                return;
            }
            let mut text_node = Map::new();
            text_node.insert("type".into(), json!("text"));
            text_node.insert("text".into(), json!(segment));
            if let Some(marks) = &marks {
                text_node.insert("marks".into(), marks.clone());
            }
            out.push(Value::Object(text_node));
        };
        let mut cursor = 0usize;
        for captures in FOOTNOTE_REF_RE.captures_iter(&text) {
            let whole = captures.get(0).expect("match");
            push_segment(&text[cursor..whole.start()], &mut out);
            let key = &captures[1];
            out.push(json!({
                "type": "footnote",
                "attrs": {
                    "content": footnotes.get(key).cloned().unwrap_or_default(),
                    "label": key,
                },
            }));
            cursor = whole.end();
        }
        push_segment(&text[cursor..], &mut out);
    }
    out
}

/// marked escapes code-span text in its tokenizer (`escape(text, true)`);
/// replicated so inline code matches the TS output byte-for-byte.
fn escape_marked_codespan(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            '\'' => out.push_str("&#39;"),
            other => out.push(other),
        }
    }
    out
}

/// Port of htmlMarkdownBlockToTipTapNodes: embedded HTML blocks go through
/// the generateJSON-equivalent converter (html_to_tiptap.rs); the
/// catch-branch falls back to markup-stripped plain text, silently.
fn html_markdown_block_to_nodes(html: &str) -> Vec<Value> {
    if html.trim().is_empty() {
        return Vec::new();
    }
    if let Ok(parsed) = html_to_tiptap::html_to_tiptap_json(html) {
        return parsed
            .get("content")
            .and_then(Value::as_array)
            .cloned()
            .unwrap_or_default();
    }
    let stripped = strip_markup(html);
    let stripped = stripped.trim();
    if stripped.is_empty() {
        Vec::new()
    } else {
        vec![json!({"type": "paragraph", "content": [{"type": "text", "text": stripped}]})]
    }
}

fn collect_html(iter: &mut MdIter) -> String {
    let mut html = String::new();
    let mut depth: usize = 0;
    while let Some((event, _)) = iter.next() {
        match event {
            Event::Html(text) | Event::Text(text) | Event::InlineHtml(text) => html.push_str(&text),
            Event::Start(_) => depth += 1,
            Event::End(TagEnd::HtmlBlock) if depth == 0 => break,
            Event::End(_) => depth = depth.saturating_sub(1),
            _ => {}
        }
    }
    html
}

fn collect_image_alt(iter: &mut MdIter) -> String {
    let mut alt = String::new();
    let mut depth: usize = 0;
    while let Some((event, _)) = iter.next() {
        match event {
            Event::Text(text) | Event::Code(text) => alt.push_str(&text),
            Event::SoftBreak | Event::HardBreak => alt.push('\n'),
            Event::Start(_) => depth += 1,
            Event::End(TagEnd::Image) if depth == 0 => break,
            Event::End(_) => depth = depth.saturating_sub(1),
            _ => {}
        }
    }
    alt
}

fn skip_until(iter: &mut MdIter, until: TagEnd) {
    let mut depth: usize = 0;
    while let Some((event, _)) = iter.next() {
        match event {
            Event::Start(_) => depth += 1,
            Event::End(tag) => {
                if depth == 0 && tag == until {
                    return;
                }
                depth = depth.saturating_sub(1);
            }
            _ => {}
        }
    }
}

// ---------------------------------------------------------------------------
// TipTap XML
// ---------------------------------------------------------------------------

const XML_MARK_TAGS: &[(&str, &str)] = &[
    ("strong", "bold"),
    ("bold", "bold"),
    ("em", "italic"),
    ("italic", "italic"),
    ("s", "strike"),
    ("strike", "strike"),
    ("code", "code"),
    ("a", "link"),
    ("link", "link"),
    ("mark", "highlight"),
    ("highlight", "highlight"),
    ("span", "textStyle"),
    ("textstyle", "textStyle"),
    ("commentmark", "commentMark"),
    ("wiremark", "wireMark"),
];

const XML_NODE_TAGS: &[(&str, &str)] = &[
    ("doc", "doc"),
    ("paragraph", "paragraph"),
    ("heading", "heading"),
    ("listitem", "listItem"),
    ("bulletlist", "bulletList"),
    ("orderedlist", "orderedList"),
    ("tasklist", "taskList"),
    ("blockquote", "blockquote"),
    ("codeblock", "codeBlock"),
    ("horizontalrule", "horizontalRule"),
    ("image", "image"),
    ("mathinline", "mathInline"),
    ("mathblock", "mathBlock"),
    ("hardbreak", "hardBreak"),
    ("footnote", "footnote"),
    ("wikilink", "wikilink"),
    ("tagchip", "tagChip"),
    ("table", "table"),
    ("tablerow", "tableRow"),
    ("tableheader", "tableHeader"),
    ("tablecell", "tableCell"),
    ("queryblock", "queryBlock"),
];

const XML_INLINE_ATOM_TYPES: &[&str] = &["footnote", "wikilink", "tagChip", "mathInline", "hardBreak"];
const XML_LEAF_BLOCK_TYPES: &[&str] = &["horizontalRule", "image", "mathBlock", "queryBlock"];
const KNOWN_TIPTAP_NODE_TYPES: &[&str] = &[
    "doc",
    "paragraph",
    "heading",
    "listItem",
    "bulletList",
    "orderedList",
    "taskList",
    "blockquote",
    "codeBlock",
    "table",
    "tableRow",
    "tableHeader",
    "tableCell",
];

pub(crate) fn tiptap_xml_to_tiptap_json(xml: &str) -> Result<Value, String> {
    if xml.trim().is_empty() {
        return Ok(json!({"type": "doc", "content": []}));
    }
    let wrapped = format!("<doc>{xml}</doc>");
    let document = roxmltree::Document::parse(&wrapped).map_err(|error| error.to_string())?;
    let content: Vec<Value> = document
        .root_element()
        .children()
        .flat_map(|child| xml_node_to_tiptap_nodes(child, &[]))
        .collect();
    Ok(json!({"type": "doc", "content": content}))
}

fn xml_node_to_tiptap_nodes(node: roxmltree::Node, marks: &[Value]) -> Vec<Value> {
    if node.is_text() {
        let text = node.text().unwrap_or("");
        // TS: skip empty and /^[\t\n\r ]+$/ whitespace-only runs.
        if text.is_empty() || text.chars().all(|c| matches!(c, '\t' | '\n' | '\r' | ' ')) {
            return Vec::new();
        }
        let mut text_node = Map::new();
        text_node.insert("type".into(), json!("text"));
        text_node.insert("text".into(), json!(text));
        if !marks.is_empty() {
            text_node.insert("marks".into(), json!(marks));
        }
        return vec![Value::Object(text_node)];
    }
    if !node.is_element() {
        return Vec::new();
    }

    let tag = node.tag_name().name();
    let lower = tag.to_lowercase();
    let node_type = XML_NODE_TAGS
        .iter()
        .find(|(t, _)| *t == lower)
        .map(|(_, v)| (*v).to_string())
        .unwrap_or_else(|| tag.to_string());
    let mark_type = XML_MARK_TAGS
        .iter()
        .find(|(t, _)| *t == lower)
        .map(|(_, v)| *v);
    let mut attrs = tiptap_attrs_from_xml_element(node);

    if let Some(mark_type) = mark_type {
        let mark = if attrs.is_empty() {
            json!({"type": mark_type})
        } else {
            json!({"type": mark_type, "attrs": attrs})
        };
        let mut next = marks.to_vec();
        next.push(mark);
        return node
            .children()
            .flat_map(|child| xml_node_to_tiptap_nodes(child, &next))
            .collect();
    }

    if XML_INLINE_ATOM_TYPES.contains(&node_type.as_str()) {
        return vec![node_with_optional_attrs(&node_type, attrs)];
    }

    if XML_LEAF_BLOCK_TYPES.contains(&node_type.as_str()) {
        let text = xml_text_content(node).trim().to_string();
        let has_src = attrs.get("src").map(js_truthy).unwrap_or(false);
        let has_query = attrs.get("query").map(js_truthy).unwrap_or(false);
        if (node_type == "mathBlock" || node_type == "queryBlock")
            && !text.is_empty()
            && !has_src
            && !has_query
        {
            if node_type == "mathBlock" {
                attrs.insert("src".into(), json!(text));
            } else {
                attrs.insert("query".into(), json!(text));
            }
        }
        return vec![node_with_optional_attrs(&node_type, attrs)];
    }

    if !KNOWN_TIPTAP_NODE_TYPES.contains(&node_type.as_str()) {
        return node
            .children()
            .flat_map(|child| xml_node_to_tiptap_nodes(child, marks))
            .collect();
    }

    let content: Vec<Value> = node
        .children()
        .flat_map(|child| xml_node_to_tiptap_nodes(child, marks))
        .collect();
    let mut out = Map::new();
    out.insert("type".into(), json!(node_type));
    if !attrs.is_empty() {
        out.insert("attrs".into(), Value::Object(attrs));
    }
    if !content.is_empty() {
        out.insert("content".into(), json!(content));
    }
    vec![Value::Object(out)]
}

fn node_with_optional_attrs(node_type: &str, attrs: Map<String, Value>) -> Value {
    let mut node = Map::new();
    node.insert("type".into(), json!(node_type));
    if !attrs.is_empty() {
        node.insert("attrs".into(), Value::Object(attrs));
    }
    Value::Object(node)
}

fn xml_text_content(node: roxmltree::Node) -> String {
    node.descendants()
        .filter(|n| n.is_text())
        .filter_map(|n| n.text())
        .collect()
}

fn tiptap_attrs_from_xml_element(node: roxmltree::Node) -> Map<String, Value> {
    let mut attrs = Map::new();
    for attr in node.attributes() {
        let key = normalize_xml_attr_name(attr.name());
        let value = coerce_xml_attr_value(&key, attr.value());
        attrs.insert(key, value);
    }
    let block_id_truthy = attrs.get("blockId").map(js_truthy).unwrap_or(false);
    let data_block_id_truthy = attrs.get("data-block-id").map(js_truthy).unwrap_or(false);
    if block_id_truthy && !data_block_id_truthy {
        if let Some(value) = attrs.remove("blockId") {
            attrs.insert("data-block-id".into(), value);
        }
    }
    for (source, target) in [
        ("data-indent", "indent"),
        ("data-list-type", "listType"),
        ("data-checked", "checked"),
        ("data-comment-id", "commentId"),
        ("data-wire-id", "wireId"),
        ("data-footnote-content", "content"),
    ] {
        if attrs.contains_key(source) && !attrs.contains_key(target) {
            if let Some(value) = attrs.get(source).cloned() {
                attrs.insert(target.into(), value);
            }
        }
    }
    attrs
}

fn normalize_xml_attr_name(name: &str) -> String {
    match name.to_lowercase().as_str() {
        "level" => "level".into(),
        "listtype" => "listType".into(),
        "commentid" => "commentId".into(),
        "wireid" => "wireId".into(),
        "targetdocid" => "targetDocId".into(),
        "targetblockid" => "targetBlockId".into(),
        "targetgraphid" => "targetGraphId".into(),
        "blockpreview" => "blockPreview".into(),
        _ => name.to_string(),
    }
}

fn coerce_xml_attr_value(key: &str, value: &str) -> Value {
    if ["level", "indent", "data-indent", "order"].contains(&key) {
        return match js_number_from_str(value) {
            Some(numeric) => number_to_json(numeric),
            None => json!(value),
        };
    }
    if [
        "checked",
        "collapsed",
        "data-checked",
        "data-collapsed",
        "resolved",
    ]
    .contains(&key)
    {
        return json!(value == "true" || value == "1");
    }
    json!(value)
}

// ---------------------------------------------------------------------------
// normalizeImportedTipTapJson — flat list model + block ids
// ---------------------------------------------------------------------------

const BLOCK_ID_TYPES: &[&str] = &[
    "paragraph",
    "heading",
    "listItem",
    "blockquote",
    "codeBlock",
    "horizontalRule",
    "image",
    "mathBlock",
];
const LIST_CONTAINERS: &[&str] = &["bulletList", "orderedList", "taskList"];
const LIST_ITEM_BLOCKS: &[&str] = &["paragraph", "heading", "codeBlock", "blockquote"];

fn normalize_imported_tiptap_json(json_value: Value, block_id_seed: Option<&str>) -> Value {
    let nodes = json_value
        .get("content")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let mut content = normalize_blocks(nodes, 0.0);
    if content.is_empty() {
        content.push(json!({"type": "paragraph"}));
    }
    let mut doc = json!({"type": "doc", "content": content});
    let mut block_ordinal = 0_u64;
    ensure_block_ids(&mut doc, block_id_seed, &mut block_ordinal);
    doc
}

fn node_type_of(node: &Value) -> &str {
    node.get("type").and_then(Value::as_str).unwrap_or("")
}

fn attrs_of(node: &Value) -> Option<&Map<String, Value>> {
    node.get("attrs").and_then(Value::as_object)
}

fn normalize_blocks(nodes: Vec<Value>, indent: f64) -> Vec<Value> {
    let mut result: Vec<Value> = Vec::new();
    for node in nodes {
        let node_type = node_type_of(&node).to_string();
        if LIST_CONTAINERS.contains(&node_type.as_str()) {
            let list_type = list_type_for_container(&node_type);
            result.extend(normalize_list_container(node, list_type, indent));
            continue;
        }
        if node_type == "listItem" {
            let list_type =
                list_type_from_attrs(attrs_of(&node)).unwrap_or_else(|| "bullet".into());
            let item_indent = indent_from_attrs(attrs_of(&node)).unwrap_or(indent);
            result.extend(normalize_list_item(node, &list_type, item_indent));
            continue;
        }
        if node_type == "doc" {
            let children = node
                .get("content")
                .and_then(Value::as_array)
                .cloned()
                .unwrap_or_default();
            result.extend(normalize_blocks(children, indent));
            continue;
        }
        result.push(normalize_block_node(node, indent));
    }
    result
}

fn normalize_list_container(node: Value, list_type: &str, indent: f64) -> Vec<Value> {
    let children = node
        .get("content")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let mut out: Vec<Value> = Vec::new();
    for child in children {
        if node_type_of(&child) == "listItem" {
            out.extend(normalize_list_item(child, list_type, indent));
        } else {
            out.extend(normalize_blocks(vec![child], indent));
        }
    }
    out
}

fn normalize_list_item(node: Value, list_type: &str, indent: f64) -> Vec<Value> {
    let children = node
        .get("content")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default();
    let mut direct_blocks: Vec<Value> = Vec::new();
    let mut nested: Vec<Value> = Vec::new();
    let mut inline: Vec<Value> = Vec::new();

    for child in children {
        let child_type = node_type_of(&child).to_string();
        if LIST_CONTAINERS.contains(&child_type.as_str()) || child_type == "listItem" {
            nested.push(child);
        } else if LIST_ITEM_BLOCKS.contains(&child_type.as_str()) {
            flush_inline(&mut inline, &mut direct_blocks);
            direct_blocks.push(normalize_block_node(child, indent));
        } else {
            inline.push(child);
        }
    }
    flush_inline(&mut inline, &mut direct_blocks);

    let mut attrs = attrs_of(&node).cloned().unwrap_or_default();
    attrs.insert("listType".into(), json!(list_type));
    attrs.insert("indent".into(), number_to_json(indent));
    if list_type == "task" {
        let original = attrs_of(&node);
        let checked_value = pick_attr(original, &["checked", "data-checked"]);
        attrs.insert(
            "checked".into(),
            json!(checked_value.map(js_truthy).unwrap_or(false)),
        );
    }

    let content = if direct_blocks.is_empty() {
        vec![json!({"type": "paragraph"})]
    } else {
        direct_blocks
    };

    let mut out = vec![json!({"type": "listItem", "attrs": attrs, "content": content})];
    for child in nested {
        let child_type = node_type_of(&child).to_string();
        if child_type == "listItem" {
            out.extend(normalize_list_item(child, list_type, indent + 1.0));
        } else {
            let container_type = list_type_for_container(&child_type);
            out.extend(normalize_list_container(
                child,
                container_type,
                indent + 1.0,
            ));
        }
    }
    out
}

fn flush_inline(inline: &mut Vec<Value>, blocks: &mut Vec<Value>) {
    if inline.is_empty() {
        return;
    }
    let content: Vec<Value> = inline.drain(..).collect();
    blocks.push(json!({"type": "paragraph", "content": content}));
}

fn normalize_block_node(node: Value, indent: f64) -> Value {
    let node_type = node_type_of(&node).to_string();
    let mut attrs = attrs_of(&node).cloned().unwrap_or_default();

    if node_type == "heading" {
        let level_value = pick_attr(attrs_of(&node), &["level"]);
        let level = level_value
            .map(js_number_of_value)
            .unwrap_or(Some(1.0))
            .filter(|l| l.is_finite())
            .unwrap_or(1.0);
        attrs.insert("level".into(), number_to_json(level.clamp(1.0, 3.0)));
    }
    if node_type == "listItem" {
        let indent_value = pick_attr(attrs_of(&node), &["indent"]);
        let numeric = match indent_value {
            Some(value) => js_number_of_value(value),
            None => Some(indent),
        };
        // JS `|| 0`: NaN and 0 collapse to 0.
        let numeric = numeric
            .filter(|n| n.is_finite() && *n != 0.0)
            .unwrap_or(0.0);
        attrs.insert("indent".into(), number_to_json(numeric));
    }

    let mut out = node.as_object().cloned().unwrap_or_default();
    if !attrs.is_empty() {
        out.insert("attrs".into(), Value::Object(attrs));
    }
    if let Some(Value::Array(children)) = node.get("content") {
        out.insert(
            "content".into(),
            json!(normalize_blocks(children.clone(), indent)),
        );
    }
    Value::Object(out)
}

fn list_type_for_container(node_type: &str) -> &'static str {
    match node_type {
        "orderedList" => "ordered",
        "taskList" => "task",
        _ => "bullet",
    }
}

fn list_type_from_attrs(attrs: Option<&Map<String, Value>>) -> Option<String> {
    let value = pick_attr(attrs, &["listType", "data-list-type"])?;
    match value {
        Value::String(s) if !s.is_empty() => Some(s.clone()),
        _ => None,
    }
}

fn indent_from_attrs(attrs: Option<&Map<String, Value>>) -> Option<f64> {
    let value = pick_attr(attrs, &["indent", "data-indent"])?;
    js_number_of_value(value).filter(|n| n.is_finite())
}

/// JS `attrs?.a ?? attrs?.b`: first key that is present and not null.
fn pick_attr<'a>(attrs: Option<&'a Map<String, Value>>, keys: &[&str]) -> Option<&'a Value> {
    let attrs = attrs?;
    for key in keys {
        if let Some(value) = attrs.get(*key) {
            if !value.is_null() {
                return Some(value);
            }
        }
    }
    None
}

fn ensure_block_ids(node: &mut Value, block_id_seed: Option<&str>, block_ordinal: &mut u64) {
    let node_type = node_type_of(node).to_string();
    if BLOCK_ID_TYPES.contains(&node_type.as_str()) {
        let ordinal = *block_ordinal;
        *block_ordinal = block_ordinal.saturating_add(1);
        if let Some(obj) = node.as_object_mut() {
            let needs_object = !matches!(obj.get("attrs"), Some(Value::Object(_)));
            if needs_object {
                obj.insert("attrs".into(), json!({}));
            }
            if let Some(Value::Object(attrs)) = obj.get_mut("attrs") {
                let has_id = attrs.get("data-block-id").map(js_truthy).unwrap_or(false)
                    || attrs.get("blockId").map(js_truthy).unwrap_or(false);
                if !has_id {
                    let id = match block_id_seed {
                        Some(seed) => deterministic_block_id(seed, ordinal),
                        None => {
                            let id = uuid::Uuid::new_v4().to_string();
                            format!("block-{}", &id[..8])
                        }
                    };
                    attrs.insert("data-block-id".into(), json!(id));
                }
            }
        }
    }
    if let Some(children) = node.get_mut("content").and_then(Value::as_array_mut) {
        for child in children {
            ensure_block_ids(child, block_id_seed, block_ordinal);
        }
    }
}

fn deterministic_block_id(operation_id: &str, ordinal: u64) -> String {
    // FNV-1a is deliberately simple and stable across Rust/toolchain versions;
    // eight hex digits preserve the frontend's `block-<uuid8>` contract.
    let mut hash = 0x811c9dc5_u32;
    for byte in operation_id
        .as_bytes()
        .iter()
        .copied()
        .chain([0_u8])
        .chain(ordinal.to_be_bytes())
    {
        hash ^= u32::from(byte);
        hash = hash.wrapping_mul(0x0100_0193);
    }
    format!("block-{hash:08x}")
}

// ---------------------------------------------------------------------------
// Title extraction
// ---------------------------------------------------------------------------

fn extract_title_from_tiptap_json(doc: &Value) -> Option<String> {
    for node in doc.get("content").and_then(Value::as_array)? {
        if node_type_of(node) != "heading" {
            continue;
        }
        let title = tiptap_node_text(node);
        let title = title.trim();
        if !title.is_empty() {
            return Some(title.to_string());
        }
    }
    None
}

fn tiptap_node_text(node: &Value) -> String {
    match node_type_of(node) {
        "text" => node
            .get("text")
            .and_then(Value::as_str)
            .unwrap_or("")
            .to_string(),
        "hardBreak" => "\n".to_string(),
        "footnote" => attr_string(node, &["content", "data-footnote-content"]),
        "wikilink" => attr_string(node, &["label", "blockPreview"]),
        "mathInline" | "mathBlock" => attr_string(node, &["src"]),
        "image" => attr_string(node, &["alt", "src"]),
        _ => node
            .get("content")
            .and_then(Value::as_array)
            .map(|children| children.iter().map(tiptap_node_text).collect::<String>())
            .unwrap_or_default(),
    }
}

fn attr_string(node: &Value, keys: &[&str]) -> String {
    match pick_attr(attrs_of(node), keys) {
        Some(value) => js_string_of_value(value),
        None => String::new(),
    }
}

// ---------------------------------------------------------------------------
// JS coercion helpers
// ---------------------------------------------------------------------------

fn js_truthy(value: &Value) -> bool {
    match value {
        Value::Null => false,
        Value::Bool(b) => *b,
        Value::Number(n) => n.as_f64().map(|f| f != 0.0).unwrap_or(true),
        Value::String(s) => !s.is_empty(),
        _ => true,
    }
}

/// JS Number(string); None means NaN.
fn js_number_from_str(value: &str) -> Option<f64> {
    let trimmed = value.trim();
    if trimmed.is_empty() {
        return Some(0.0);
    }
    trimmed.parse::<f64>().ok().filter(|f| f.is_finite())
}

/// JS Number(value) over JSON values; None means NaN.
fn js_number_of_value(value: &Value) -> Option<f64> {
    match value {
        Value::Number(n) => n.as_f64(),
        Value::String(s) => js_number_from_str(s),
        Value::Bool(b) => Some(if *b { 1.0 } else { 0.0 }),
        Value::Null => Some(0.0),
        _ => None,
    }
}

fn js_string_of_value(value: &Value) -> String {
    match value {
        Value::String(s) => s.clone(),
        Value::Bool(b) => b.to_string(),
        Value::Number(n) => match n.as_i64() {
            Some(i) => i.to_string(),
            None => n.to_string(),
        },
        _ => String::new(),
    }
}

/// Serialize like JSON.stringify: integral numbers without a fraction.
fn number_to_json(value: f64) -> Value {
    if value.fract() == 0.0 && value.abs() < i64::MAX as f64 {
        json!(value as i64)
    } else {
        json!(value)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn xml_inline_atoms_preserve_types_attributes_and_literal_text() {
        let parsed = parse_write_content_for_operation(
            "<paragraph data-block-id=\"p\">before <tagChip name=\"todo\" date=\"2026-09-12\"></tagChip><wikilink label=\"Visible\" targetDocId=\"target\"></wikilink><footnote content=\"A &amp; B\"></footnote> after</paragraph>",
            Some("xml"),"parser-atoms").unwrap();
        assert!(parsed.warnings.is_empty());
        let content = parsed.tiptap_json["content"][0]["content"].as_array().unwrap();
        assert_eq!(content.len(),5);
        assert_eq!(content[1],json!({"type":"tagChip","attrs":{"name":"todo","date":"2026-09-12"}}));
        assert_eq!(content[2],json!({"type":"wikilink","attrs":{"label":"Visible","targetDocId":"target"}}));
        assert_eq!(content[3],json!({"type":"footnote","attrs":{"content":"A & B"}}));
        let literal = parse_write_content_for_operation(
            "<paragraph data-block-id=\"p\">&lt;tagChip name=\"todo\"&gt;&lt;/tagChip&gt;</paragraph>",
            Some("xml"),"parser-literal").unwrap();
        assert!(literal.warnings.is_empty());
        assert_eq!(literal.tiptap_json["content"][0]["content"][0],
            json!({"type":"text","text":"<tagChip name=\"todo\"></tagChip>"}));
    }

    #[test]
    fn detects_formats_like_ts() {
        assert_eq!(resolve_write_content_format("", None), "plain");
        assert_eq!(resolve_write_content_format("# Hi", None), "markdown");
        assert_eq!(resolve_write_content_format("just text", None), "plain");
        assert_eq!(resolve_write_content_format("<p>hello</p>", None), "html");
        assert_eq!(
            resolve_write_content_format("<paragraph>hello</paragraph>", None),
            "xml"
        );
        // explicit format wins; unknown values mean auto (writeContentFormat)
        assert_eq!(resolve_write_content_format("# Hi", Some("plain")), "plain");
        assert_eq!(
            resolve_write_content_format("# Hi", Some("auto")),
            "markdown"
        );
        assert_eq!(
            resolve_write_content_format("# Hi", Some("bogus")),
            "markdown"
        );
    }

    #[test]
    fn html_format_parses_via_converter() {
        let parsed = parse_write_content("<p>Hello <b>world</b></p>", Some("html")).unwrap();
        assert_eq!(parsed.source_format, "html");
        assert!(parsed.warnings.is_empty());
        let paragraph = &parsed.tiptap_json["content"][0];
        assert_eq!(paragraph["type"], "paragraph");
        assert_eq!(tiptap_node_text(paragraph), "Hello world");
        assert_eq!(paragraph["content"][1]["marks"][0]["type"], "bold");
    }

    #[test]
    fn invalid_xml_falls_back_with_warning() {
        let parsed = parse_write_content("<paragraph>broken", Some("xml")).unwrap();
        assert_eq!(parsed.source_format, "xml");
        assert_eq!(parsed.warnings.len(), 1);
        assert!(parsed.warnings[0].starts_with("Content parse fallback:"));
        // fallback strips markup and keeps the text
        let text = tiptap_node_text(&parsed.tiptap_json["content"][0]);
        assert_eq!(text, "broken");
    }
}
