//! HTML → garden-schema TipTap JSON, port of the frontend's html write path:
//! frontend/src/native/artifact-ingest.ts parseTipTapWriteContent (html branch)
//! = prepareHtmlForTipTapImport (script/style/noscript/template removal +
//! flattenHtmlLists nested→flat list rewrite) followed by TipTap's
//! `generateJSON(html, EXPORT_EXTENSIONS)`, i.e. ProseMirror's DOMParser over
//! the schema compiled from frontend/src/lib/tiptap-export-extensions.ts.
//!
//! The output is the RAW generateJSON-equivalent TipTap JSON; callers feed it
//! through `normalize_imported_tiptap_json` (content_parse.rs) exactly like
//! the TS does. Verified against fixtures generated by running the actual TS
//! path: frontend/scripts/generate-html-tiptap-fixtures.test.mts →
//! tests/fixtures/html_to_tiptap/ → tests/html_to_tiptap.rs.
//!
//! Faithfulness notes:
//! - HTML parsing uses html5ever (via `scraper`), the same spec algorithm
//!   browsers use; the TS path parses with jsdom (prepare pass) + happy-dom
//!   (generateJSON). Divergences are limited to non-spec-compliant happy-dom
//!   corners (e.g. `<image>` → `<img>` coercion).
//! - The ProseMirror DOMParser core (prosemirror-model 1.25.4 from_dom.ts:
//!   ParseContext / NodeContext, whitespace normalization, findPlace
//!   wrapping, blockTags sync, leaf fallbacks, Fragment text-node merging,
//!   required-content filling) is ported against a hardcoded mini-schema
//!   matching the compiled EXPORT_EXTENSIONS schema (node content
//!   expressions, attribute defaults, tag/style rule order, mark rank order).
//! - Unsupported-by-design (never produced by web content; documented gaps):
//!   footnote / wikilink / mathInline / mathBlock / commentMark parse rules
//!   (`<footnote>`, `span[data-footnote]`, `span[data-comment-id]`,
//!   `span[data-math-inline]`, `div[data-math-block]`) — these elements fall
//!   through to the unknown-element (transparent) path instead.
//! - `colspan`/`rowspan` are parsed as strings when present (TipTap's default
//!   attribute parse is `getAttribute`), defaulting to the number 1 —
//!   matching the TS byte-for-byte.

#![allow(dead_code)]

use serde_json::{json, Map, Value};
use std::collections::HashSet;
use std::sync::LazyLock;

// ─────────────────────────────────────────────────────────────────────────────
// Simple owned DOM (built from scraper/html5ever, mutable for list flattening)
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub(crate) enum DomNode {
    Element(DomElement),
    Text(String),
}

#[derive(Debug, Clone)]
pub(crate) struct DomElement {
    pub(crate) tag: String,
    pub(crate) attrs: Vec<(String, String)>,
    pub(crate) children: Vec<DomNode>,
}

impl DomElement {
    pub(crate) fn attr(&self, name: &str) -> Option<&str> {
        self.attrs
            .iter()
            .find(|(key, _)| key == name)
            .map(|(_, value)| value.as_str())
    }

    fn set_attr(&mut self, name: &str, value: String) {
        if let Some(entry) = self.attrs.iter_mut().find(|(key, _)| key == name) {
            entry.1 = value;
        } else {
            self.attrs.push((name.to_string(), value));
        }
    }

    fn has_class(&self, class: &str) -> bool {
        self.attr("class")
            .map(|value| value.split_ascii_whitespace().any(|c| c == class))
            .unwrap_or(false)
    }

    /// Inline-style property lookup (lowercased property names).
    fn style_prop(&self, prop: &str) -> Option<String> {
        let style = self.attr("style")?;
        for decl in style.split(';') {
            let mut parts = decl.splitn(2, ':');
            let name = parts.next()?.trim().to_lowercase();
            if name == prop {
                return Some(parts.next().unwrap_or("").trim().to_string());
            }
        }
        None
    }

    fn first_element_child(&self) -> Option<&DomElement> {
        self.children.iter().find_map(|child| match child {
            DomNode::Element(el) => Some(el),
            _ => None,
        })
    }

    fn first_descendant_img(&self) -> Option<&DomElement> {
        for child in &self.children {
            if let DomNode::Element(el) = child {
                if el.tag == "img" {
                    return Some(el);
                }
                if let Some(found) = el.first_descendant_img() {
                    return Some(found);
                }
            }
        }
        None
    }
}

/// Tags removed up-front by prepareHtmlForTipTapImport.
const PREPARE_REMOVE_TAGS: &[&str] = &["script", "style", "noscript", "template"];

/// Parse `html` and return the `<body>` element as an owned tree, with the
/// prepare-pass removals applied.
pub(crate) fn build_body_dom(html: &str) -> DomElement {
    let parsed = scraper::Html::parse_document(html);
    let selector = scraper::Selector::parse("body").expect("valid selector");
    match parsed.select(&selector).next() {
        Some(body) => convert_element(body),
        None => DomElement {
            tag: "body".into(),
            attrs: Vec::new(),
            children: Vec::new(),
        },
    }
}

pub(crate) fn convert_element(el: scraper::ElementRef) -> DomElement {
    let tag = el.value().name().to_lowercase();
    let attrs: Vec<(String, String)> = el
        .value()
        .attrs()
        .map(|(name, value)| (name.to_lowercase(), value.to_string()))
        .collect();
    let mut children: Vec<DomNode> = Vec::new();
    for child in el.children() {
        match child.value() {
            scraper::Node::Text(text) => {
                // DOM semantics: contiguous text is one text node.
                if let Some(DomNode::Text(last)) = children.last_mut() {
                    last.push_str(text);
                } else {
                    children.push(DomNode::Text(text.to_string()));
                }
            }
            scraper::Node::Element(element) => {
                let child_tag = element.name().to_lowercase();
                if PREPARE_REMOVE_TAGS.contains(&child_tag.as_str()) {
                    continue;
                }
                if let Some(child_ref) = scraper::ElementRef::wrap(child) {
                    children.push(DomNode::Element(convert_element(child_ref)));
                }
            }
            _ => {}
        }
    }
    DomElement {
        tag,
        attrs,
        children,
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// flattenHtmlLists (artifact-ingest.ts): nested <ul>/<ol> → flat li sequence
// with data-list-type / data-indent / data-checked.
// ─────────────────────────────────────────────────────────────────────────────

pub(crate) fn flatten_html_lists(root: &mut DomElement) {
    flatten_walk(root, false);
}

fn flatten_walk(el: &mut DomElement, inside_li: bool) {
    for child in el.children.iter_mut() {
        let DomNode::Element(child_el) = child else {
            continue;
        };
        let is_list = child_el.tag == "ul" || child_el.tag == "ol";
        if is_list && !inside_li {
            let mut flat = DomElement {
                tag: child_el.tag.clone(),
                attrs: Vec::new(),
                children: Vec::new(),
            };
            append_flattened_list_items(child_el, &mut flat, 0);
            *child_el = flat;
            // The replacement flat list is not re-processed (TS snapshot
            // semantics: querySelectorAll ran before any replaceWith).
            continue;
        }
        let next_inside_li = inside_li || child_el.tag == "li";
        flatten_walk(child_el, next_inside_li);
    }
}

fn append_flattened_list_items(list: &DomElement, target: &mut DomElement, indent: usize) {
    let default_type = if list.tag == "ol" {
        "ordered"
    } else {
        "bullet"
    };
    for item in &list.children {
        let DomNode::Element(item_el) = item else {
            continue;
        };
        if item_el.tag != "li" {
            continue;
        }
        let mut clone = item_el.clone();
        clone.children.retain(
            |child| !matches!(child, DomNode::Element(el) if el.tag == "ul" || el.tag == "ol"),
        );
        let checkbox_checked = remove_first_own_checkbox(&mut clone);
        let list_type = if checkbox_checked.is_some() {
            "task"
        } else {
            default_type
        };
        clone.set_attr("data-list-type", list_type.to_string());
        clone.set_attr("data-indent", indent.to_string());
        if let Some(checked) = checkbox_checked {
            clone.set_attr(
                "data-checked",
                if checked { "true" } else { "false" }.to_string(),
            );
        }
        target.children.push(DomNode::Element(clone));
        for nested in &item_el.children {
            if let DomNode::Element(el) = nested {
                if el.tag == "ul" || el.tag == "ol" {
                    append_flattened_list_items(el, target, indent + 1);
                }
            }
        }
    }
}

/// Port of firstOwnCheckbox + removal: the first `input[type=checkbox]`
/// descendant whose nearest `li` ancestor is the item itself. Returns its
/// checked state after removing it.
fn remove_first_own_checkbox(item: &mut DomElement) -> Option<bool> {
    fn walk(el: &mut DomElement) -> Option<bool> {
        let mut found: Option<(usize, bool)> = None;
        for (index, child) in el.children.iter().enumerate() {
            if let DomNode::Element(child_el) = child {
                if child_el.tag == "input"
                    && child_el
                        .attr("type")
                        .map(|t| t.eq_ignore_ascii_case("checkbox"))
                        .unwrap_or(false)
                {
                    found = Some((index, child_el.attr("checked").is_some()));
                    break;
                }
            }
        }
        if let Some((index, checked)) = found {
            el.children.remove(index);
            return Some(checked);
        }
        for child in el.children.iter_mut() {
            if let DomNode::Element(child_el) = child {
                if child_el.tag == "li" {
                    continue; // belongs to a nested item
                }
                if let Some(checked) = walk(child_el) {
                    return Some(checked);
                }
            }
        }
        None
    }
    walk(item)
}

/// prosemirror-model normalizeList: move list elements that directly follow a
/// `li` sibling into that `li` (invalid-HTML fixup). Applied to every list.
fn normalize_lists_recursive(el: &mut DomElement) {
    if el.tag == "ul" || el.tag == "ol" {
        let mut index = 0usize;
        let mut prev_item: Option<usize> = None;
        while index < el.children.len() {
            let tag = match &el.children[index] {
                DomNode::Element(child) => Some(child.tag.clone()),
                _ => None,
            };
            match tag.as_deref() {
                Some("ul") | Some("ol") if prev_item.is_some() => {
                    let moved = el.children.remove(index);
                    if let Some(prev) = prev_item {
                        if let DomNode::Element(prev_el) = &mut el.children[prev] {
                            prev_el.children.push(moved);
                        }
                    }
                    // resume at the element that shifted into `index`
                }
                Some("li") => {
                    prev_item = Some(index);
                    index += 1;
                }
                Some(_) => {
                    prev_item = None;
                    index += 1;
                }
                None => {
                    index += 1;
                }
            }
        }
    }
    for child in el.children.iter_mut() {
        if let DomNode::Element(child_el) = child {
            normalize_lists_recursive(child_el);
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// Mini schema (compiled EXPORT_EXTENSIONS schema, from the fixture dump)
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
enum Nt {
    Doc,
    Paragraph,
    Heading,
    Blockquote,
    CodeBlock,
    HorizontalRule,
    Image,
    ListItem,
    Table,
    TableRow,
    TableHeader,
    TableCell,
    HardBreak,
    Text,
}

impl Nt {
    fn name(self) -> &'static str {
        match self {
            Nt::Doc => "doc",
            Nt::Paragraph => "paragraph",
            Nt::Heading => "heading",
            Nt::Blockquote => "blockquote",
            Nt::CodeBlock => "codeBlock",
            Nt::HorizontalRule => "horizontalRule",
            Nt::Image => "image",
            Nt::ListItem => "listItem",
            Nt::Table => "table",
            Nt::TableRow => "tableRow",
            Nt::TableHeader => "tableHeader",
            Nt::TableCell => "tableCell",
            Nt::HardBreak => "hardBreak",
            Nt::Text => "text",
        }
    }

    fn is_inline(self) -> bool {
        matches!(self, Nt::Text | Nt::HardBreak)
    }

    fn is_leaf(self) -> bool {
        matches!(
            self,
            Nt::Text | Nt::HardBreak | Nt::HorizontalRule | Nt::Image
        )
    }

    fn inline_content(self) -> bool {
        matches!(self, Nt::Paragraph | Nt::Heading | Nt::CodeBlock)
    }

    /// Whether marks survive on children inserted directly into this node
    /// (NodeType.allowsMarkType): inline-content nodes allow all marks except
    /// codeBlock (`marks: ""`); block-content nodes allow none.
    fn allows_marks(self) -> bool {
        matches!(self, Nt::Paragraph | Nt::Heading)
    }

    /// Allowed direct children, in compiled-schema match order (drives
    /// findWrapping BFS order).
    fn allowed_children(self) -> &'static [Nt] {
        const BLOCKS: &[Nt] = &[
            Nt::Paragraph,
            Nt::Blockquote,
            Nt::Heading,
            Nt::HorizontalRule,
            Nt::CodeBlock,
            Nt::Table,
            Nt::ListItem,
            Nt::Image,
        ];
        const INLINE: &[Nt] = &[Nt::Text, Nt::HardBreak];
        match self {
            Nt::Doc | Nt::Blockquote | Nt::TableHeader | Nt::TableCell => BLOCKS,
            Nt::Paragraph | Nt::Heading => INLINE,
            Nt::CodeBlock => &[Nt::Text],
            Nt::ListItem => &[Nt::Paragraph, Nt::Heading, Nt::CodeBlock, Nt::Blockquote],
            Nt::Table => &[Nt::TableRow],
            Nt::TableRow => &[Nt::TableCell, Nt::TableHeader],
            _ => &[],
        }
    }

    /// Content expressions ending in `+` (must hold at least one child).
    fn requires_content(self) -> bool {
        matches!(
            self,
            Nt::Doc | Nt::Blockquote | Nt::ListItem | Nt::Table | Nt::TableHeader | Nt::TableCell
        )
    }

    fn fits(self, child: Nt) -> bool {
        self.allowed_children().contains(&child)
    }
}

/// ContentMatch.findWrapping: shortest chain of wrapper node types so that
/// `target` fits inside `parent`. Empty vec = fits directly.
fn find_wrapping(parent: Nt, target: Nt) -> Option<Vec<Nt>> {
    if parent.fits(target) {
        return Some(Vec::new());
    }
    let mut seen: HashSet<Nt> = HashSet::new();
    let mut queue: std::collections::VecDeque<(Nt, Vec<Nt>)> = Default::default();
    for &child in parent.allowed_children() {
        if !child.is_leaf() && seen.insert(child) {
            queue.push_back((child, vec![child]));
        }
    }
    while let Some((node_type, route)) = queue.pop_front() {
        if node_type.fits(target) {
            return Some(route);
        }
        for &child in node_type.allowed_children() {
            if !child.is_leaf() && seen.insert(child) {
                let mut next = route.clone();
                next.push(child);
                queue.push_back((child, next));
            }
        }
    }
    None
}

// ─────────────────────────────────────────────────────────────────────────────
// Marks
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, PartialEq)]
struct MarkInst {
    rank: u8,
    name: &'static str,
    attrs: Map<String, Value>,
}

impl MarkInst {
    fn simple(rank: u8, name: &'static str) -> Self {
        MarkInst {
            rank,
            name,
            attrs: Map::new(),
        }
    }

    fn to_json(&self) -> Value {
        if self.attrs.is_empty() {
            json!({"type": self.name})
        } else {
            json!({"type": self.name, "attrs": self.attrs})
        }
    }
}

// Mark rank order from the compiled schema:
// link, textStyle, bold, code, italic, strike, underline, highlight
const RANK_LINK: u8 = 0;
const RANK_TEXT_STYLE: u8 = 1;
const RANK_BOLD: u8 = 2;
const RANK_CODE: u8 = 3;
const RANK_ITALIC: u8 = 4;
const RANK_STRIKE: u8 = 5;
const RANK_UNDERLINE: u8 = 6;
const RANK_HIGHLIGHT: u8 = 7;

/// Mark.addToSet over a rank-sorted set: same-type marks are replaced.
fn add_to_set(set: &mut Vec<MarkInst>, mark: MarkInst) {
    if set
        .iter()
        .any(|existing| existing.name == mark.name && existing.attrs == mark.attrs)
    {
        return;
    }
    set.retain(|existing| existing.name != mark.name);
    let position = set
        .iter()
        .position(|existing| existing.rank > mark.rank)
        .unwrap_or(set.len());
    set.insert(position, mark);
}

fn marks_to_json(marks: &[MarkInst]) -> Value {
    Value::Array(marks.iter().map(MarkInst::to_json).collect())
}

// ─────────────────────────────────────────────────────────────────────────────
// Attribute computation (TipTap attribute parseHTML + defaults)
// ─────────────────────────────────────────────────────────────────────────────

const SOURCE_METADATA_ATTRIBUTES: &[&str] = &[
    "data-source-format",
    "data-source-approach",
    "data-source-page",
    "data-source-role",
    "data-source-id",
    "data-pdf-page",
    "data-pdf-role",
];

fn attr_or_null(el: Option<&DomElement>, name: &str) -> Value {
    el.and_then(|el| el.attr(name))
        .map(|value| json!(value))
        .unwrap_or(Value::Null)
}

fn source_metadata_attrs(map: &mut Map<String, Value>, el: Option<&DomElement>) {
    for name in SOURCE_METADATA_ATTRIBUTES {
        map.insert((*name).to_string(), attr_or_null(el, name));
    }
}

fn block_id_attr(map: &mut Map<String, Value>, el: Option<&DomElement>) {
    map.insert(
        "data-block-id".to_string(),
        attr_or_null(el, "data-block-id"),
    );
}

/// TextAlign parseHTML: element.style.textAlign if in the allowed alignments.
fn text_align_attr(map: &mut Map<String, Value>, el: Option<&DomElement>) {
    let alignment = el
        .and_then(|el| el.style_prop("text-align"))
        .filter(|value| {
            ["left", "center", "right", "justify"].contains(&value.to_lowercase().as_str())
        })
        .map(|value| json!(value.to_lowercase()))
        .unwrap_or(Value::Null);
    map.insert("textAlign".to_string(), alignment);
}

/// Outliner / ListItem indent: parseInt(data-indent, 10) else 0.
fn indent_attr(map: &mut Map<String, Value>, el: Option<&DomElement>) {
    let indent = el
        .and_then(|el| el.attr("data-indent"))
        .filter(|value| !value.is_empty())
        .and_then(parse_int_prefix)
        .unwrap_or(0);
    map.insert("indent".to_string(), json!(indent));
}

fn collapsed_attr(map: &mut Map<String, Value>, el: Option<&DomElement>) {
    let collapsed = el
        .and_then(|el| el.attr("data-collapsed"))
        .map(|value| value == "true")
        .unwrap_or(false);
    map.insert("collapsed".to_string(), json!(collapsed));
}

/// JS parseInt(value, 10): optional sign + leading digits.
fn parse_int_prefix(value: &str) -> Option<i64> {
    let trimmed = value.trim_start();
    let (sign, digits) = match trimmed.strip_prefix('-') {
        Some(rest) => (-1i64, rest),
        None => (1i64, trimmed.strip_prefix('+').unwrap_or(trimmed)),
    };
    let end = digits
        .char_indices()
        .take_while(|(_, c)| c.is_ascii_digit())
        .map(|(i, c)| i + c.len_utf8())
        .last()?;
    digits[..end].parse::<i64>().ok().map(|n| n * sign)
}

/// Attrs for a node created by a tag rule (`el` present) or synthesized as a
/// wrapper/filler (`el` absent → pure defaults). `heading_level` carries the
/// static rule attr for h1..h3.
fn node_attrs(
    nt: Nt,
    el: Option<&DomElement>,
    parent: Option<&DomElement>,
    heading_level: Option<i64>,
) -> Map<String, Value> {
    let mut map = Map::new();
    match nt {
        Nt::Paragraph | Nt::Heading => {
            block_id_attr(&mut map, el);
            source_metadata_attrs(&mut map, el);
            text_align_attr(&mut map, el);
            indent_attr(&mut map, el);
            collapsed_attr(&mut map, el);
            if nt == Nt::Heading {
                map.insert("level".to_string(), json!(heading_level.unwrap_or(1)));
            }
        }
        Nt::Blockquote => {
            block_id_attr(&mut map, el);
            source_metadata_attrs(&mut map, el);
            indent_attr(&mut map, el);
            collapsed_attr(&mut map, el);
        }
        Nt::HorizontalRule => {
            block_id_attr(&mut map, el);
            source_metadata_attrs(&mut map, el);
        }
        Nt::CodeBlock => {
            block_id_attr(&mut map, el);
            source_metadata_attrs(&mut map, el);
            // CodeBlock language: language-<x> class on the first element
            // child (the <code>).
            let language = el
                .and_then(|el| el.first_element_child())
                .and_then(|code| code.attr("class"))
                .and_then(|classes| {
                    classes
                        .split_ascii_whitespace()
                        .find_map(|class| class.strip_prefix("language-"))
                        .map(|language| language.to_string())
                })
                .filter(|language| !language.is_empty())
                .map(|language| json!(language))
                .unwrap_or(Value::Null);
            map.insert("language".to_string(), language);
        }
        Nt::ListItem => {
            block_id_attr(&mut map, el);
            source_metadata_attrs(&mut map, el);
            indent_attr(&mut map, el);
            collapsed_attr(&mut map, el);
            // ListItem listType: data-list-type, else inferred from parent.
            let list_type = el
                .and_then(|el| el.attr("data-list-type"))
                .filter(|value| !value.is_empty())
                .map(|value| value.to_string())
                .or_else(|| {
                    let parent = parent?;
                    if parent.tag == "ol" {
                        Some("ordered".to_string())
                    } else if parent.attr("data-type") == Some("taskList") {
                        Some("task".to_string())
                    } else {
                        Some("bullet".to_string())
                    }
                })
                .unwrap_or_else(|| "bullet".to_string());
            map.insert("listType".to_string(), json!(list_type));
            let checked = el
                .and_then(|el| el.attr("data-checked"))
                .map(|value| value == "true")
                .unwrap_or(false);
            map.insert("checked".to_string(), json!(checked));
        }
        Nt::Image => {
            block_id_attr(&mut map, el);
            source_metadata_attrs(&mut map, el);
            // ImageBlock parseHTML: prefer the <img> child when the matched
            // element is a wrapper (div.image-block).
            let img = el.and_then(|el| {
                if el.tag == "img" {
                    Some(el)
                } else {
                    el.first_descendant_img()
                }
            });
            let pick = |name: &str| -> Option<String> {
                img.and_then(|img| img.attr(name))
                    .filter(|value| !value.is_empty())
                    .or_else(|| el.and_then(|el| el.attr(name)).filter(|v| !v.is_empty()))
                    .map(|value| value.to_string())
            };
            map.insert(
                "src".to_string(),
                pick("src").map(|v| json!(v)).unwrap_or(Value::Null),
            );
            map.insert("alt".to_string(), json!(pick("alt").unwrap_or_default()));
            map.insert(
                "title".to_string(),
                pick("title").map(|v| json!(v)).unwrap_or(Value::Null),
            );
            let size = el
                .and_then(|el| el.attr("data-size"))
                .filter(|value| !value.is_empty())
                .unwrap_or("large");
            map.insert("size".to_string(), json!(size));
        }
        Nt::Table => {
            source_metadata_attrs(&mut map, el);
            indent_attr(&mut map, el);
            collapsed_attr(&mut map, el);
        }
        Nt::TableRow => {
            source_metadata_attrs(&mut map, el);
        }
        Nt::TableHeader | Nt::TableCell => {
            source_metadata_attrs(&mut map, el);
            // TipTap default attribute parse: getAttribute → string when
            // present; numeric default 1 otherwise.
            for name in ["colspan", "rowspan"] {
                let value = el
                    .and_then(|el| el.attr(name))
                    .map(|value| json!(value))
                    .unwrap_or(json!(1));
                map.insert(name.to_string(), value);
            }
            let colwidth = el
                .and_then(|el| el.attr("colwidth"))
                .filter(|value| !value.is_empty())
                .map(|value| {
                    Value::Array(
                        value
                            .split(',')
                            .map(|part| {
                                parse_int_prefix(part)
                                    .map(|n| json!(n))
                                    .unwrap_or(Value::Null)
                            })
                            .collect(),
                    )
                })
                .unwrap_or(Value::Null);
            map.insert("colwidth".to_string(), colwidth);
        }
        Nt::Doc | Nt::HardBreak | Nt::Text => {}
    }
    map
}

// ─────────────────────────────────────────────────────────────────────────────
// Tag + style rules
// ─────────────────────────────────────────────────────────────────────────────

enum RuleOut {
    Node {
        nt: Nt,
        attrs: Map<String, Value>,
        preserve_full: bool,
    },
    Mark(MarkInst),
    NoRule,
    Ignore,
}

static ALLOWED_URI_RE: LazyLock<regex::Regex> = LazyLock::new(|| {
    regex::Regex::new(
        r"(?i)^(?:(?:http|https|ftp|ftps|mailto|tel|callto|sms|cid|xmpp):|[^a-zA-Z]|[a-zA-Z0-9+.\-]+(?:[^a-zA-Z+.\-:]|$))",
    )
    .expect("valid regex")
});

/// Port of @tiptap/extension-link isAllowedUri (whitespace stripped first).
fn is_allowed_uri(uri: &str) -> bool {
    let stripped: String = uri.chars().filter(|c| !is_js_whitespace(*c)).collect();
    stripped.is_empty() || ALLOWED_URI_RE.is_match(&stripped)
}

pub(crate) fn is_js_whitespace(c: char) -> bool {
    matches!(
        c,
        '\t' | '\n' | '\u{b}' | '\u{c}' | '\r' | ' ' | '\u{a0}' | '\u{1680}' | '\u{2000}'
            ..='\u{200a}'
                | '\u{2028}'
                | '\u{2029}'
                | '\u{202f}'
                | '\u{205f}'
                | '\u{3000}'
                | '\u{feff}'
    )
}

const IGNORE_TAGS: &[&str] = &["head", "noscript", "object", "script", "style", "title"];

const BLOCK_TAGS: &[&str] = &[
    "address",
    "article",
    "aside",
    "blockquote",
    "canvas",
    "dd",
    "div",
    "dl",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "header",
    "hgroup",
    "hr",
    "li",
    "noscript",
    "ol",
    "output",
    "p",
    "pre",
    "section",
    "table",
    "tfoot",
    "ul",
];

fn match_tag(el: &DomElement, parent: Option<&DomElement>) -> RuleOut {
    let tag = el.tag.as_str();
    match tag {
        "a" => {
            if let Some(href) = el.attr("href") {
                if !href.is_empty() && is_allowed_uri(href) {
                    let mut attrs = Map::new();
                    attrs.insert("href".to_string(), json!(href));
                    attrs.insert(
                        "target".to_string(),
                        json!(el.attr("target").unwrap_or("_blank")),
                    );
                    attrs.insert(
                        "rel".to_string(),
                        json!(el.attr("rel").unwrap_or("noopener noreferrer nofollow")),
                    );
                    attrs.insert(
                        "class".to_string(),
                        json!(el.attr("class").unwrap_or("editor-link")),
                    );
                    return RuleOut::Mark(MarkInst {
                        rank: RANK_LINK,
                        name: "link",
                        attrs,
                    });
                }
            }
            RuleOut::NoRule
        }
        "span" => {
            // TextStyle: span with a style attribute (consuming: false; the
            // remaining span rules are the unsupported comment/footnote/math
            // ones, so the element is otherwise transparent).
            if el.attr("style").is_some() {
                let mut attrs = Map::new();
                attrs.insert(
                    "fontFamily".to_string(),
                    json!(el.style_prop("font-family").unwrap_or_default()),
                );
                attrs.insert(
                    "fontSize".to_string(),
                    json!(el.style_prop("font-size").unwrap_or_default()),
                );
                return RuleOut::Mark(MarkInst {
                    rank: RANK_TEXT_STYLE,
                    name: "textStyle",
                    attrs,
                });
            }
            RuleOut::NoRule
        }
        "strong" => RuleOut::Mark(MarkInst::simple(RANK_BOLD, "bold")),
        "b" => {
            // getAttrs: node.style.fontWeight !== 'normal'
            if el.style_prop("font-weight").as_deref() == Some("normal") {
                RuleOut::NoRule
            } else {
                RuleOut::Mark(MarkInst::simple(RANK_BOLD, "bold"))
            }
        }
        "code" => RuleOut::Mark(MarkInst::simple(RANK_CODE, "code")),
        "em" => RuleOut::Mark(MarkInst::simple(RANK_ITALIC, "italic")),
        "i" => {
            if el.style_prop("font-style").as_deref() == Some("normal") {
                RuleOut::NoRule
            } else {
                RuleOut::Mark(MarkInst::simple(RANK_ITALIC, "italic"))
            }
        }
        "s" | "del" | "strike" => RuleOut::Mark(MarkInst::simple(RANK_STRIKE, "strike")),
        "u" => RuleOut::Mark(MarkInst::simple(RANK_UNDERLINE, "underline")),
        "mark" => RuleOut::Mark(MarkInst::simple(RANK_HIGHLIGHT, "highlight")),
        "p" => RuleOut::Node {
            nt: Nt::Paragraph,
            attrs: node_attrs(Nt::Paragraph, Some(el), parent, None),
            preserve_full: false,
        },
        "blockquote" => RuleOut::Node {
            nt: Nt::Blockquote,
            attrs: node_attrs(Nt::Blockquote, Some(el), parent, None),
            preserve_full: false,
        },
        "br" => RuleOut::Node {
            nt: Nt::HardBreak,
            attrs: Map::new(),
            preserve_full: false,
        },
        "h1" | "h2" | "h3" => {
            let level = tag[1..].parse::<i64>().unwrap_or(1);
            RuleOut::Node {
                nt: Nt::Heading,
                attrs: node_attrs(Nt::Heading, Some(el), parent, Some(level)),
                preserve_full: false,
            }
        }
        "hr" => RuleOut::Node {
            nt: Nt::HorizontalRule,
            attrs: node_attrs(Nt::HorizontalRule, Some(el), parent, None),
            preserve_full: false,
        },
        "pre" => RuleOut::Node {
            nt: Nt::CodeBlock,
            attrs: node_attrs(Nt::CodeBlock, Some(el), parent, None),
            preserve_full: true,
        },
        "table" => RuleOut::Node {
            nt: Nt::Table,
            attrs: node_attrs(Nt::Table, Some(el), parent, None),
            preserve_full: false,
        },
        "tr" => RuleOut::Node {
            nt: Nt::TableRow,
            attrs: node_attrs(Nt::TableRow, Some(el), parent, None),
            preserve_full: false,
        },
        "th" => RuleOut::Node {
            nt: Nt::TableHeader,
            attrs: node_attrs(Nt::TableHeader, Some(el), parent, None),
            preserve_full: false,
        },
        "td" => RuleOut::Node {
            nt: Nt::TableCell,
            attrs: node_attrs(Nt::TableCell, Some(el), parent, None),
            preserve_full: false,
        },
        "li" => RuleOut::Node {
            nt: Nt::ListItem,
            attrs: node_attrs(Nt::ListItem, Some(el), parent, None),
            preserve_full: false,
        },
        "img" => {
            if el.attr("src").is_some() {
                RuleOut::Node {
                    nt: Nt::Image,
                    attrs: node_attrs(Nt::Image, Some(el), parent, None),
                    preserve_full: false,
                }
            } else {
                RuleOut::NoRule
            }
        }
        "image" => {
            if el.attr("src").is_some() {
                RuleOut::Node {
                    nt: Nt::Image,
                    attrs: node_attrs(Nt::Image, Some(el), parent, None),
                    preserve_full: false,
                }
            } else {
                RuleOut::NoRule
            }
        }
        "div" if el.has_class("image-block") => RuleOut::Node {
            nt: Nt::Image,
            attrs: node_attrs(Nt::Image, Some(el), parent, None),
            preserve_full: false,
        },
        _ if IGNORE_TAGS.contains(&tag) => RuleOut::Ignore,
        _ => RuleOut::NoRule,
    }
}

static BOLD_WEIGHT_RE: LazyLock<regex::Regex> =
    LazyLock::new(|| regex::Regex::new(r"^(bold(er)?|[5-9]\d{2,})$").expect("valid regex"));

/// Port of ParseContext.readStyles over the compiled style-rule list:
/// font-weight=400 (clear bold), font-weight bold-ish (add bold),
/// font-style=normal (clear italic), font-style=italic (add italic),
/// text-decoration line-through (strike), text-decoration underline.
fn read_styles(el: &DomElement, marks: &[MarkInst]) -> Vec<MarkInst> {
    let mut out = marks.to_vec();
    if let Some(value) = el.style_prop("font-weight") {
        if value == "400" {
            out.retain(|m| m.name != "bold");
        } else if BOLD_WEIGHT_RE.is_match(&value) {
            out.push(MarkInst::simple(RANK_BOLD, "bold"));
        }
    }
    if let Some(value) = el.style_prop("font-style") {
        if value == "normal" {
            out.retain(|m| m.name != "italic");
        } else if value == "italic" {
            out.push(MarkInst::simple(RANK_ITALIC, "italic"));
        }
    }
    if let Some(value) = el.style_prop("text-decoration") {
        if value.contains("line-through") {
            out.push(MarkInst::simple(RANK_STRIKE, "strike"));
        }
        if value.contains("underline") {
            out.push(MarkInst::simple(RANK_UNDERLINE, "underline"));
        }
    }
    out
}

// ─────────────────────────────────────────────────────────────────────────────
// ParseContext port (prosemirror-model from_dom.ts)
// ─────────────────────────────────────────────────────────────────────────────

const OPT_PRESERVE_WS: u8 = 1;
const OPT_PRESERVE_WS_FULL: u8 = 2;

fn ws_options_for(nt: Nt, preserve_full: Option<bool>, base: u8) -> u8 {
    match preserve_full {
        Some(true) => OPT_PRESERVE_WS | OPT_PRESERVE_WS_FULL,
        Some(false) => OPT_PRESERVE_WS,
        None => {
            if nt == Nt::CodeBlock {
                // whitespace: "pre" (code: true)
                OPT_PRESERVE_WS | OPT_PRESERVE_WS_FULL
            } else {
                base
            }
        }
    }
}

struct NodeCtx {
    id: u64,
    nt: Nt,
    attrs: Map<String, Value>,
    content: Vec<Value>,
    solid: bool,
    options: u8,
}

impl NodeCtx {
    /// NodeContext.finish(openEnd=false): trailing-whitespace strip, adjacent
    /// text merge (Fragment.fromArray) and required-content fill.
    fn finish(mut self) -> Value {
        if self.options & OPT_PRESERVE_WS == 0 {
            if let Some(last) = self.content.last_mut() {
                if last.get("type").and_then(Value::as_str) == Some("text") {
                    let text = last
                        .get("text")
                        .and_then(Value::as_str)
                        .unwrap_or_default()
                        .to_string();
                    let stripped = text.trim_end_matches([' ', '\t', '\r', '\n', '\u{c}']);
                    if stripped.is_empty() {
                        self.content.pop();
                    } else if stripped.len() != text.len() {
                        last["text"] = json!(stripped);
                    }
                }
            }
        }
        let mut merged: Vec<Value> = Vec::new();
        for node in self.content {
            let is_text = node.get("type").and_then(Value::as_str) == Some("text");
            if is_text {
                if let Some(prev) = merged.last_mut() {
                    let prev_is_text = prev.get("type").and_then(Value::as_str) == Some("text");
                    if prev_is_text && prev.get("marks") == node.get("marks") {
                        let combined = format!(
                            "{}{}",
                            prev.get("text").and_then(Value::as_str).unwrap_or(""),
                            node.get("text").and_then(Value::as_str).unwrap_or("")
                        );
                        prev["text"] = json!(combined);
                        continue;
                    }
                }
            }
            merged.push(node);
        }
        if merged.is_empty() && self.nt.requires_content() {
            merged.push(default_fill(self.nt));
        }
        let mut out = Map::new();
        out.insert("type".to_string(), json!(self.nt.name()));
        if !self.attrs.is_empty() {
            out.insert("attrs".to_string(), Value::Object(self.attrs));
        }
        if !merged.is_empty() {
            out.insert("content".to_string(), json!(merged));
        }
        Value::Object(out)
    }
}

/// ContentMatch.fillBefore: the default node created to satisfy a `+`
/// expression (first allowed child type, recursively filled).
fn default_fill(parent: Nt) -> Value {
    let child = parent.allowed_children()[0];
    let mut out = Map::new();
    out.insert("type".to_string(), json!(child.name()));
    let attrs = node_attrs(child, None, None, None);
    if !attrs.is_empty() {
        out.insert("attrs".to_string(), Value::Object(attrs));
    }
    if child.requires_content() {
        out.insert("content".to_string(), json!([default_fill(child)]));
    }
    Value::Object(out)
}

struct Parser {
    nodes: Vec<NodeCtx>,
    open: usize,
    local_preserve_ws: bool,
    next_id: u64,
}

impl Parser {
    fn new() -> Self {
        Parser {
            nodes: vec![NodeCtx {
                id: 0,
                nt: Nt::Doc,
                attrs: Map::new(),
                content: Vec::new(),
                solid: true,
                options: 0,
            }],
            open: 0,
            local_preserve_ws: false,
            next_id: 1,
        }
    }

    fn top(&self) -> &NodeCtx {
        &self.nodes[self.open]
    }

    fn top_mut(&mut self) -> &mut NodeCtx {
        &mut self.nodes[self.open]
    }

    fn add_all(&mut self, el: &DomElement, marks: &[MarkInst]) {
        // domNodeBefore: whether the previous DOM sibling is a <br> element.
        let mut prev_is_br = false;
        for child in &el.children {
            match child {
                DomNode::Text(text) => {
                    self.add_text_node(text, prev_is_br, marks);
                    prev_is_br = false;
                }
                DomNode::Element(child_el) => {
                    self.add_element(child_el, marks, Some(el));
                    prev_is_br = child_el.tag == "br";
                }
            }
        }
    }

    // Port of addTextNode. `prev_is_br`: the previous DOM sibling is a <br>.
    fn add_text_node(&mut self, value: &str, prev_is_br: bool, marks: &[MarkInst]) {
        let top = self.top();
        let preserve_full = top.options & OPT_PRESERVE_WS_FULL != 0;
        let preserve = self.local_preserve_ws || top.options & OPT_PRESERVE_WS != 0;
        let has_non_ws = value
            .chars()
            .any(|c| !matches!(c, ' ' | '\t' | '\r' | '\n' | '\u{c}'));
        let inline_context = top.nt.inline_content();
        if !(preserve_full || inline_context || has_non_ws) {
            return;
        }
        let mut text = value.to_string();
        if !preserve {
            text = collapse_html_ws(&text);
            if text.starts_with(' ') && self.open == self.nodes.len() - 1 {
                let node_before = self.top().content.last();
                let before_is_ws_text = node_before
                    .map(|node| {
                        node.get("type").and_then(Value::as_str) == Some("text")
                            && node
                                .get("text")
                                .and_then(Value::as_str)
                                .map(|t| t.ends_with([' ', '\t', '\r', '\n', '\u{c}']))
                                .unwrap_or(false)
                    })
                    .unwrap_or(false);
                if node_before.is_none() || prev_is_br || before_is_ws_text {
                    text.remove(0);
                }
            }
        } else if preserve_full {
            text = text.replace("\r\n", "\n").replace('\r', "\n");
        } else if text.contains(['\r', '\n'])
            && find_wrapping(self.top().nt, Nt::HardBreak).is_some()
        {
            // linebreakReplacement (hardBreak) path for preserve-ws contexts.
            let lines: Vec<String> = text
                .replace("\r\n", "\n")
                .replace('\r', "\n")
                .split('\n')
                .map(|line| line.to_string())
                .collect();
            for (index, line) in lines.iter().enumerate() {
                if index > 0 {
                    self.insert_leaf(Nt::HardBreak, Map::new(), marks, true);
                }
                if !line.is_empty() {
                    let all_ws = !line.chars().any(|c| !is_js_whitespace(c));
                    self.insert_text(line.clone(), marks, all_ws);
                }
            }
            return;
        } else {
            text = text.replace("\r\n", " ").replace(['\r', '\n'], " ");
        }
        if !text.is_empty() {
            let all_ws = !text.chars().any(|c| !is_js_whitespace(c));
            self.insert_text(text, marks, all_ws);
        }
    }

    fn add_element(&mut self, el: &DomElement, marks: &[MarkInst], parent: Option<&DomElement>) {
        let outer_ws = self.local_preserve_ws;
        if el.tag == "pre"
            || el
                .style_prop("white-space")
                .map(|value| value.contains("pre"))
                .unwrap_or(false)
        {
            self.local_preserve_ws = true;
        }
        match match_tag(el, parent) {
            RuleOut::Ignore => {}
            RuleOut::NoRule => {
                let mut sync_id: Option<u64> = None;
                let block_tag = BLOCK_TAGS.contains(&el.tag.as_str());
                if block_tag {
                    let first_is_inline = self
                        .top()
                        .content
                        .first()
                        .map(is_inline_json)
                        .unwrap_or(false);
                    if !self.top().content.is_empty() && first_is_inline && self.open > 0 {
                        self.open -= 1;
                    }
                    sync_id = Some(self.top().id);
                } else if el.children.is_empty() {
                    self.leaf_fallback(el, marks);
                    self.local_preserve_ws = outer_ws;
                    return;
                }
                let inner = read_styles(el, marks);
                self.add_all(el, &inner);
                if let Some(id) = sync_id {
                    self.sync_to_id(id);
                }
            }
            RuleOut::Mark(mark) => {
                let mut inner = read_styles(el, marks);
                inner.push(mark);
                self.add_all(el, &inner);
            }
            RuleOut::Node {
                nt,
                attrs,
                preserve_full,
            } => {
                let inner = read_styles(el, marks);
                if nt.is_leaf() {
                    if !self.insert_leaf(nt, attrs, &inner, el.tag == "br") {
                        self.leaf_fallback(el, &inner);
                    }
                } else {
                    let preserve = if preserve_full { Some(true) } else { None };
                    let entered = self.enter(nt, attrs, preserve);
                    let start_id = self.top().id;
                    self.add_all(el, &inner);
                    if entered && self.sync_to_id(start_id) {
                        self.open = self.open.saturating_sub(1);
                    }
                }
            }
        }
        self.local_preserve_ws = outer_ws;
    }

    // leafFallback: a <br> that could not be inserted becomes "\n" when the
    // top node has inline content (e.g. inside codeBlock).
    fn leaf_fallback(&mut self, el: &DomElement, marks: &[MarkInst]) {
        if el.tag == "br" && self.top().nt.inline_content() {
            self.add_text_node("\n", false, marks);
        }
    }

    fn insert_text(&mut self, text: String, marks: &[MarkInst], cautious: bool) -> bool {
        let node = json!({"type": "text", "text": text});
        self.insert_node(node, Nt::Text, marks, cautious)
    }

    fn insert_leaf(
        &mut self,
        nt: Nt,
        attrs: Map<String, Value>,
        marks: &[MarkInst],
        cautious: bool,
    ) -> bool {
        let mut node = Map::new();
        node.insert("type".to_string(), json!(nt.name()));
        if !attrs.is_empty() {
            node.insert("attrs".to_string(), Value::Object(attrs));
        }
        self.insert_node(Value::Object(node), nt, marks, cautious)
    }

    // Port of insertNode + findPlace.
    fn insert_node(&mut self, mut node: Value, nt: Nt, marks: &[MarkInst], cautious: bool) -> bool {
        if !self.find_place(nt, cautious) {
            return false;
        }
        self.close_extra();
        let top_allows_marks = self.top().nt.allows_marks();
        if top_allows_marks && !marks.is_empty() {
            let mut set: Vec<MarkInst> = Vec::new();
            for mark in marks {
                add_to_set(&mut set, mark.clone());
            }
            if !set.is_empty() {
                node["marks"] = marks_to_json(&set);
            }
        }
        self.top_mut().content.push(node);
        true
    }

    // findPlace: search depths open..0 for the shortest wrapping (with the
    // solid-node penalty), sync there, and enter the wrappers.
    fn find_place(&mut self, nt: Nt, cautious: bool) -> bool {
        let mut route: Option<Vec<Nt>> = None;
        let mut sync_idx: Option<usize> = None;
        let mut penalty = 0usize;
        for depth in (0..=self.open).rev() {
            let cx = &self.nodes[depth];
            if let Some(found) = find_wrapping(cx.nt, nt) {
                let better = match &route {
                    None => true,
                    Some(existing) => existing.len() > found.len() + penalty,
                };
                if better {
                    let empty = found.is_empty();
                    route = Some(found);
                    sync_idx = Some(depth);
                    if empty {
                        break;
                    }
                }
            }
            if cx.solid {
                if cautious {
                    break;
                }
                penalty += 2;
            }
        }
        let Some(route) = route else {
            return false;
        };
        if let Some(idx) = sync_idx {
            self.sync_to_id(self.nodes[idx].id);
        }
        for wrapper in route {
            self.enter_inner(wrapper, node_attrs(wrapper, None, None, None), false, None);
        }
        true
    }

    fn enter(&mut self, nt: Nt, attrs: Map<String, Value>, preserve: Option<bool>) -> bool {
        if !self.find_place(nt, false) {
            return false;
        }
        self.enter_inner(nt, attrs, true, preserve);
        true
    }

    fn enter_inner(
        &mut self,
        nt: Nt,
        attrs: Map<String, Value>,
        solid: bool,
        preserve: Option<bool>,
    ) {
        self.close_extra();
        let options = ws_options_for(nt, preserve, self.top().options);
        let id = self.next_id;
        self.next_id += 1;
        self.nodes.push(NodeCtx {
            id,
            nt,
            attrs,
            content: Vec::new(),
            solid,
            options,
        });
        self.open += 1;
    }

    fn close_extra(&mut self) {
        while self.nodes.len() - 1 > self.open {
            let ctx = self.nodes.pop().expect("non-empty stack");
            let finished = ctx.finish();
            self.nodes
                .last_mut()
                .expect("parent exists")
                .content
                .push(finished);
        }
    }

    // Port of sync(to): find the context by identity; set open. While
    // localPreserveWS is set, contexts scanned over get the WS bit.
    fn sync_to_id(&mut self, id: u64) -> bool {
        for index in (0..=self.open).rev() {
            if self.nodes[index].id == id {
                self.open = index;
                return true;
            }
            if self.local_preserve_ws {
                self.nodes[index].options |= OPT_PRESERVE_WS;
            }
        }
        false
    }

    fn finish(mut self) -> Value {
        self.open = 0;
        self.close_extra();
        self.nodes.pop().expect("doc context").finish()
    }
}

fn is_inline_json(node: &Value) -> bool {
    matches!(
        node.get("type").and_then(Value::as_str),
        Some("text") | Some("hardBreak")
    )
}

/// HTML whitespace collapse: runs of [ \t\r\n\f] → single space.
fn collapse_html_ws(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    let mut in_ws = false;
    for c in value.chars() {
        if matches!(c, ' ' | '\t' | '\r' | '\n' | '\u{c}') {
            if !in_ws {
                out.push(' ');
                in_ws = true;
            }
        } else {
            out.push(c);
            in_ws = false;
        }
    }
    out
}

// ─────────────────────────────────────────────────────────────────────────────
// Entry point
// ─────────────────────────────────────────────────────────────────────────────

/// Port of the TS html write path: prepareHtmlForTipTapImport +
/// generateJSON(html, EXPORT_EXTENSIONS). Returns raw (un-normalized) TipTap
/// JSON: `{type: "doc", content: [...]}`. Feed the result through
/// `normalize_imported_tiptap_json` like the TS pipeline does.
pub(crate) fn html_to_tiptap_json(html: &str) -> Result<Value, String> {
    let mut body = build_body_dom(html);
    flatten_html_lists(&mut body);
    normalize_lists_recursive(&mut body);
    let mut parser = Parser::new();
    parser.add_all(&body, &[]);
    Ok(parser.finish())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_html_yields_filled_doc() {
        let doc = html_to_tiptap_json("").unwrap();
        assert_eq!(doc["type"], "doc");
        let content = doc["content"].as_array().unwrap();
        assert_eq!(content.len(), 1);
        assert_eq!(content[0]["type"], "paragraph");
    }

    #[test]
    fn basic_paragraph_with_marks() {
        let doc = html_to_tiptap_json("<p>a <strong>b</strong></p>").unwrap();
        let para = &doc["content"][0];
        assert_eq!(para["type"], "paragraph");
        assert_eq!(para["content"][0]["text"], "a ");
        assert_eq!(para["content"][1]["marks"][0]["type"], "bold");
    }

    #[test]
    fn nested_list_flattens() {
        let doc = html_to_tiptap_json("<ul><li>a<ul><li>b</li></ul></li></ul>").unwrap();
        let content = doc["content"].as_array().unwrap();
        assert_eq!(content.len(), 2);
        assert_eq!(content[0]["attrs"]["indent"], 0);
        assert_eq!(content[1]["attrs"]["indent"], 1);
        assert_eq!(content[1]["attrs"]["listType"], "bullet");
    }

    #[test]
    fn mark_order_follows_schema_rank() {
        // <em><strong>… nests italic outside bold; output is rank-sorted.
        let doc = html_to_tiptap_json("<p><em><strong>x</strong></em></p>").unwrap();
        let marks = doc["content"][0]["content"][0]["marks"].as_array().unwrap();
        assert_eq!(marks[0]["type"], "bold");
        assert_eq!(marks[1]["type"], "italic");
    }
}
