use crate::{
    ingestion_approach_types::IngestionApproachDescriptor, pdf_pipeline::PDF_FAST_TEXT_ENGINE_ID,
};

pub(crate) fn static_ingestion_approaches_before_pdf_runtime() -> Vec<IngestionApproachDescriptor> {
    vec![
        IngestionApproachDescriptor {
            approach_id: "markdown.direct".to_string(),
            label: "Markdown Direct".to_string(),
            family: "markdown".to_string(),
            status: "available".to_string(),
            runtime: "local-js".to_string(),
            file_types: vec!["md".to_string(), "markdown".to_string()],
            mime_types: vec!["text/markdown".to_string(), "text/x-markdown".to_string()],
            speed: "fast".to_string(),
            fidelity: "high".to_string(),
            output: "tiptap-json".to_string(),
            setup_required: false,
            selectable: true,
            default_for: vec!["md".to_string(), "markdown".to_string()],
            supports_ocr: false,
            supports_tables: true,
            supports_page_anchors: false,
            supports_original_view: true,
            supports_source_annotations: true,
            dependency_summary: "marked".to_string(),
            best_for: vec!["notes".to_string(), "technical documents".to_string()],
            limitations: vec!["wikilink-to-wire resolution is a separate pass".to_string()],
        },
        IngestionApproachDescriptor {
            approach_id: "html.readable".to_string(),
            label: "HTML Readable".to_string(),
            family: "html".to_string(),
            status: "available".to_string(),
            runtime: "local-js-dom".to_string(),
            file_types: vec!["html".to_string(), "htm".to_string()],
            mime_types: vec!["text/html".to_string(), "application/xhtml+xml".to_string()],
            speed: "fast".to_string(),
            fidelity: "medium-high".to_string(),
            output: "tiptap-json".to_string(),
            setup_required: false,
            selectable: true,
            default_for: vec!["html".to_string(), "htm".to_string()],
            supports_ocr: false,
            supports_tables: true,
            supports_page_anchors: false,
            supports_original_view: true,
            supports_source_annotations: true,
            dependency_summary: "browser DOM parser".to_string(),
            best_for: vec!["saved pages".to_string(), "reports".to_string()],
            limitations: vec!["interactive scripts and page chrome are stripped".to_string()],
        },
        IngestionApproachDescriptor {
            approach_id: "epub.spine-html".to_string(),
            label: "EPUB Spine HTML".to_string(),
            family: "epub".to_string(),
            status: "available".to_string(),
            runtime: "local-js-zip".to_string(),
            file_types: vec!["epub".to_string()],
            mime_types: vec!["application/epub+zip".to_string()],
            speed: "medium".to_string(),
            fidelity: "medium-high".to_string(),
            output: "book-folder-and-chapters".to_string(),
            setup_required: false,
            selectable: true,
            default_for: vec!["epub".to_string()],
            supports_ocr: false,
            supports_tables: true,
            supports_page_anchors: false,
            supports_original_view: true,
            supports_source_annotations: true,
            dependency_summary: "fflate plus OPF spine parsing".to_string(),
            best_for: vec!["books".to_string(), "chaptered documents".to_string()],
            limitations: vec![
                "complex publisher scripts are stripped in original preview".to_string()
            ],
        },
        IngestionApproachDescriptor {
            approach_id: PDF_FAST_TEXT_ENGINE_ID.to_string(),
            label: "PDF Fast Text".to_string(),
            family: "pdf".to_string(),
            status: "available".to_string(),
            runtime: "local-js-pdf".to_string(),
            file_types: vec!["pdf".to_string()],
            mime_types: vec!["application/pdf".to_string()],
            speed: "fast".to_string(),
            fidelity: "medium".to_string(),
            output: "page-aware-tiptap-json".to_string(),
            setup_required: false,
            selectable: true,
            default_for: vec!["pdf".to_string()],
            supports_ocr: false,
            supports_tables: true,
            supports_page_anchors: true,
            supports_original_view: true,
            supports_source_annotations: false,
            dependency_summary: "PDF.js text extraction".to_string(),
            best_for: vec!["searchable PDFs".to_string(), "papers".to_string()],
            limitations: vec![
                "scanned PDFs need OCR".to_string(),
                "heading/list detection is heuristic".to_string(),
            ],
        },
    ]
}

pub(crate) fn plain_text_ingestion_approach() -> IngestionApproachDescriptor {
    IngestionApproachDescriptor {
        approach_id: "text.plain".to_string(),
        label: "Plain Text".to_string(),
        family: "text".to_string(),
        status: "available".to_string(),
        runtime: "local-js".to_string(),
        file_types: vec!["txt".to_string(), "text".to_string()],
        mime_types: vec!["text/plain".to_string()],
        speed: "fast".to_string(),
        fidelity: "plain".to_string(),
        output: "tiptap-json".to_string(),
        setup_required: false,
        selectable: true,
        default_for: vec!["txt".to_string()],
        supports_ocr: false,
        supports_tables: false,
        supports_page_anchors: false,
        supports_original_view: true,
        supports_source_annotations: true,
        dependency_summary: "built-in UTF-8 decoder".to_string(),
        best_for: vec!["logs".to_string(), "plain text exports".to_string()],
        limitations: vec!["formatting is not inferred".to_string()],
    }
}
