use crate::loopback_scope_types::{scope, LoopbackScopeDetail};

pub(crate) const LOOPBACK_WORKSPACE_SCOPES: &[LoopbackScopeDetail] = &[
    scope(
        "documents.read",
        "documents",
        "read",
        "Read local documents and block projections.",
    ),
    scope(
        "documents.write.crdt",
        "documents",
        "write",
        "Write local document state through the CRDT operation path.",
    ),
    scope(
        "documents.delete.crdt",
        "documents",
        "delete",
        "Delete local documents through the CRDT operation path.",
    ),
    scope(
        "documents.history.read",
        "documents",
        "read",
        "Read local document snapshot history.",
    ),
    scope(
        "documents.snapshots.write",
        "documents",
        "write",
        "Create local document snapshots.",
    ),
    scope(
        "documents.snapshots.delete",
        "documents",
        "delete",
        "Delete local document snapshots.",
    ),
    scope(
        "workspace.read",
        "workspace",
        "read",
        "Read local workspace projections.",
    ),
    scope(
        "workspace.write.crdt",
        "workspace",
        "write",
        "Write local workspace state through the CRDT operation path.",
    ),
    scope(
        "workspace.delete.crdt",
        "workspace",
        "delete",
        "Delete local workspace entities through the CRDT operation path.",
    ),
    scope(
        "artifacts.read",
        "artifacts",
        "read",
        "Read local artifact bytes and metadata.",
    ),
    scope(
        "artifacts.write",
        "artifacts",
        "write",
        "Upload local artifact bytes.",
    ),
    scope(
        "artifacts.delete",
        "artifacts",
        "delete",
        "Delete local artifacts.",
    ),
    scope(
        "artifacts.ingest",
        "artifacts",
        "write",
        "Run local artifact ingestion.",
    ),
    scope(
        "images.read",
        "artifacts",
        "read",
        "Read local inline document images.",
    ),
    scope(
        "images.write",
        "artifacts",
        "write",
        "Upload local inline document images.",
    ),
    scope(
        "rdf.query",
        "rdf",
        "read",
        "Run read-only SPARQL queries against local RDF.",
    ),
    scope(
        "rdf.update",
        "rdf",
        "write",
        "Run SPARQL UPDATE against local RDF.",
    ),
    scope(
        "rdf.load",
        "rdf",
        "write",
        "Load RDF data into a local graph.",
    ),
    scope(
        "rdf.dump",
        "rdf",
        "read",
        "Dump RDF data from a local graph.",
    ),
    scope(
        "search.lexical.read",
        "search",
        "read",
        "Run local lexical search.",
    ),
    scope(
        "search.semantic.read",
        "search",
        "read",
        "Run local semantic search.",
    ),
    scope("wires.read", "wires", "read", "Read local semantic wires."),
    scope(
        "wires.write",
        "wires",
        "write",
        "Create or refresh local semantic wires.",
    ),
    scope(
        "wires.delete",
        "wires",
        "delete",
        "Delete local semantic wires.",
    ),
    scope(
        "entities.read",
        "entities",
        "read",
        "Read local entity records.",
    ),
    scope(
        "entities.write",
        "entities",
        "write",
        "Create or update local entity records.",
    ),
    scope(
        "entities.delete",
        "entities",
        "delete",
        "Delete local entity records.",
    ),
    scope(
        "imports.web.write",
        "imports",
        "write",
        "Import local documents from web sources.",
    ),
    scope(
        "time-travel.read",
        "time-travel",
        "read",
        "List, read, and diff local restore points.",
    ),
    scope(
        "time-travel.write",
        "time-travel",
        "write",
        "Capture or delete local restore points.",
    ),
    scope(
        "time-travel.restore",
        "time-travel",
        "write",
        "Apply or roll back a local restore point — affects every document in the graph.",
    ),
];
