use crate::{
    pdf_pipeline_catalog::{
        PdfEngineRuntimeKind, PdfEngineSpec, PDF_DOCLING_ENGINE_ID, PDF_FAST_TEXT_ENGINE_ID,
        PDF_GROBID_ENGINE_ID, PDF_OCRMYPDF_ENGINE_ID, PDF_PYMUPDF_ENGINE_ID,
    },
    pdf_runtimes::{PYMUPDF4LLM_PACKAGE_REQUIREMENT, PYMUPDF_PACKAGE_REQUIREMENT},
};

pub(crate) fn pdf_pipeline_engine_specs() -> Vec<PdfEngineSpec> {
    vec![
        PdfEngineSpec {
            engine_id: PDF_FAST_TEXT_ENGINE_ID,
            label: "PDF Fast Text",
            preference_label: "Fast Text",
            preference_description: "Always use the optimized PDF.js text path.",
            runtime: "local-js-pdf",
            role: "baseline",
            speed: "fast",
            fidelity: "medium",
            output: "page-aware-tiptap-json",
            implemented: true,
            selectable: true,
            auto_select: true,
            auto_priority: 100,
            supports_ocr: false,
            supports_tables: true,
            supports_page_anchors: true,
            supports_original_view: true,
            supports_source_annotations: false,
            best_for: &["searchable PDFs", "fast local import", "Mac Intel fallback"],
            capabilities: &[
                "PDF.js text extraction",
                "two-column reading order",
                "repeated header/footer removal",
                "heading/list/table/quote heuristics",
                "page anchors and original PDF preservation",
                "yields between pages to keep the WebView responsive",
            ],
            limitations: &[
                "no OCR for scanned pages",
                "layout semantics remain heuristic",
                "source annotations are not projected from PDF coordinates yet",
            ],
            setup_hint: None,
            adapter_pending_reason: None,
            runtime_kind: PdfEngineRuntimeKind::BuiltIn,
        },
        PdfEngineSpec {
            engine_id: PDF_DOCLING_ENGINE_ID,
            label: "Docling Accurate",
            preference_label: "Docling",
            preference_description: "Prefer Docling when its local Python runtime is available.",
            runtime: "local-python-docling",
            role: "accurate",
            speed: "slow",
            fidelity: "high",
            output: "markdown-bridged-tiptap-json",
            implemented: true,
            selectable: true,
            auto_select: true,
            auto_priority: 10,
            supports_ocr: true,
            supports_tables: true,
            supports_page_anchors: true,
            supports_original_view: true,
            supports_source_annotations: false,
            best_for: &[
                "layout-heavy reports",
                "table-heavy PDFs",
                "scanned pages when runtime support exists",
            ],
            capabilities: &[
                "local Python sidecar",
                "Docling Markdown export",
                "RapidOCR cache isolation",
                "read-only document import with preserved original bytes",
            ],
            limitations: &[
                "accurate PDF parsing runs as a local Python/Docling runtime and can take minutes on CPU",
            ],
            setup_hint: None,
            adapter_pending_reason: None,
            runtime_kind: PdfEngineRuntimeKind::Docling,
        },
        PdfEngineSpec {
            engine_id: PDF_PYMUPDF_ENGINE_ID,
            label: "PyMuPDF4LLM Structured",
            preference_label: "PyMuPDF4LLM",
            preference_description:
                "Use the slower structured Markdown parser for academic and column-heavy PDFs.",
            runtime: "local-python-pymupdf4llm",
            role: "structured-academic-pdf",
            speed: "slow",
            fidelity: "medium-high",
            output: "markdown-bridged-tiptap-json",
            implemented: true,
            selectable: true,
            auto_select: false,
            auto_priority: 20,
            supports_ocr: false,
            supports_tables: true,
            supports_page_anchors: true,
            supports_original_view: true,
            supports_source_annotations: false,
            best_for: &[
                "searchable technical PDFs",
                "academic papers with columns",
                "Mac Intel local parsing",
                "structured Markdown over raw speed",
            ],
            capabilities: &[
                "structured Markdown extraction",
                "better column order on academic papers than the fast path",
                "no Torch dependency expected",
                "runs as an async local job",
            ],
            limitations: &[
                "much slower than pdf.fast-text on larger papers",
                "scanned PDFs still need a separate OCR prepass",
                "cancellation can interrupt the external parser process but cannot recover partial pages",
            ],
            setup_hint: Some(
                "Install pymupdf4llm in a Python 3.10+ runtime, or keep uv available so the local runtime can provision it on demand.",
            ),
            adapter_pending_reason: None,
            runtime_kind: PdfEngineRuntimeKind::PythonModuleOrUv {
                env_var: "MNEMOSYNE_PYMUPDF_PYTHON",
                module_name: "pymupdf4llm",
                command_candidates: &["python3", "python"],
                uv_packages: &[PYMUPDF4LLM_PACKAGE_REQUIREMENT, PYMUPDF_PACKAGE_REQUIREMENT],
            },
        },
        PdfEngineSpec {
            engine_id: PDF_OCRMYPDF_ENGINE_ID,
            label: "OCRmyPDF + Tesseract",
            preference_label: "OCRmyPDF",
            preference_description:
                "Save the scanned-PDF OCR preference while the adapter is in progress.",
            runtime: "local-cli-ocrmypdf-tesseract",
            role: "ocr-prepass",
            speed: "slow",
            fidelity: "ocr-dependent",
            output: "searchable-pdf-then-fast-text",
            implemented: false,
            selectable: true,
            auto_select: false,
            auto_priority: 60,
            supports_ocr: true,
            supports_tables: false,
            supports_page_anchors: true,
            supports_original_view: true,
            supports_source_annotations: false,
            best_for: &["scanned PDFs", "image-only archives"],
            capabilities: &[
                "OCR prepass candidate",
                "keeps fast-text as the downstream parser",
                "Mac Intel compatible dependency shape",
            ],
            limitations: &[
                "OCR quality depends on scan quality and installed languages",
                "layout reconstruction after OCR remains heuristic",
            ],
            setup_hint: Some(
                "Install ocrmypdf and tesseract on PATH to prepare the scanned-PDF runtime.",
            ),
            adapter_pending_reason: Some("execution adapter is not wired yet"),
            runtime_kind: PdfEngineRuntimeKind::CliCommands {
                commands: &["ocrmypdf", "tesseract"],
            },
        },
        PdfEngineSpec {
            engine_id: PDF_GROBID_ENGINE_ID,
            label: "GROBID Paper Parser",
            preference_label: "GROBID",
            preference_description: "Save the scholarly-PDF preference while the adapter is in progress.",
            runtime: "local-grobid-service",
            role: "scholarly-pdf",
            speed: "medium",
            fidelity: "paper-structured",
            output: "tei-bridged-tiptap-json",
            implemented: false,
            selectable: true,
            auto_select: false,
            auto_priority: 70,
            supports_ocr: false,
            supports_tables: false,
            supports_page_anchors: true,
            supports_original_view: true,
            supports_source_annotations: false,
            best_for: &["academic papers", "metadata and bibliography extraction"],
            capabilities: &[
                "scholarly structure candidate",
                "title/abstract/reference extraction target",
                "separate from general PDF layout parsing",
            ],
            limitations: &["not a general-purpose scanned document parser"],
            setup_hint: Some(
                "Run a local GROBID service and set MNEMOSYNE_GROBID_URL when the adapter slice is enabled.",
            ),
            adapter_pending_reason: Some("execution adapter is not wired yet"),
            runtime_kind: PdfEngineRuntimeKind::ServiceUrl {
                env_vars: &["MNEMOSYNE_GROBID_URL", "GROBID_URL"],
            },
        },
    ]
}
